#pragma once

//#define HW_PLATFORM_OPENIPC 1
#define HW_PLATFORM_RASPBERRY 1

#ifdef HW_PLATFORM_RASPBERRY
#define HW_CAPABILITY_GPIO 1
#define HW_CAPABILITY_I2C 1
#define HW_CAPABILITY_IONICE 1
#endif