/*
    Ruby Licence
    Copyright (c) 2025 Petru Soroaga petrusoroaga@yahoo.com
    All rights reserved.

    Redistribution and/or use in source and/or binary forms, with or without
    modification, are permitted provided that the following conditions are met:
        * Redistributions and/or use of the source code (partially or complete) must retain
        the above copyright notice, this list of conditions and the following disclaimer
        in the documentation and/or other materials provided with the distribution.
        * Redistributions in binary form (partially or complete) must reproduce
        the above copyright notice, this list of conditions and the following disclaimer
        in the documentation and/or other materials provided with the distribution.
        * Copyright info and developer info must be preserved as is in the user
        interface, additions could be made to that info.
        * Neither the name of the organization nor the
        names of its contributors may be used to endorse or promote products
        derived from this software without specific prior written permission.
        * Military use is not permitted.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE AUTHOR (PETRU SOROAGA) BE LIABLE FOR ANY
    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "../base/base.h"
#include <ctype.h>
#include "strings_table.h"

#if defined (HW_PLATFORM_RADXA) || defined (HW_PLATFORM_RASPBERRY)

type_localized_strings s_LocalizedStringsTable[] = 
{
  //-------------------------------------------------
  // Common string

  {"Yes", "是", "Oui", "Ja", "हाँ", "Да", "Sí", 0},
  {"No", "否", "Non", "Nein", "नहीं", "Нет", "No", 0},
  {"Auto", "自动", "Auto", "Auto", "", "Автоопределение", "Auto", 0},
  {"Manual", "手动", "Manuel", "Handbuch", "", "Руководство", "Manual", 0},
  {"On", "开启", "Activé", "Aktiviert", "", "Активирован", "Activado", 0},
  {"Off", "关闭", "Désactivé", "Aus", "", "Выключенный", "Apagado", 0},
  {"Cancel", "取消", "Annuler", "Stornieren", "", "Отмена", "Cancelar", 0},
  {"Back", "后退", "Dos", "Zurück", "", "Назад", "Atrás", 0},
  {"Ok", "好的", "D'accord", "OK", "", "Хорошо", "De acuerdo", 0},
  {"None", "无", "Aucun", "Keiner", "", "Никто", "Ninguno", 0},
  {"Default", "默认", "Défaut", "Standard", "", "По умолчанию", "Por defecto", 0},
  {"Custom", "自定义", "Coutume", "Brauch", "", "Обычай", "Costumbre", 0},
  {"Info", "信息", "Informations", "Info", "", "Информация", "Información", 0},
  {"Enabled", "已启用", "Activé", "Ermöglicht", "", "Включено", "Activado", 0},
  {"Disabled", "已禁用", "Désactivé", "Deaktiviert", "", "Неполноценный", "Desactivado", 0},

  //------------------------------------------------------------
  // Formated strings

  {"(The default telemetry serial port speed it %d bps)", "（默认遥测串口速度为%d bps）", "", "", "", "", "", 0},
  {"Connected to %s", "已连接到 %s", "Connecté à %s", "Verbunden mit %s", "", "Подключено к %s", "Conectado a %s", 0},
  {"Looking for %s", "正在查找 %s", "À la recherche de %s", "Suche nach %s", "", "Ищу %s", "Buscando %s", 0},
  {"Select your %s board type", "选择您的 %s 主板类型", "Sélectionnez votre type de carte %s", "Wählen Sie Ihren %s Boardtyp", "", "Выберите тип доски %s", "Seleccione su tipo de tablero %s", 0},
  {"Your %s was updated. It will reboot now.", "您的 %s 更新完成，它将立即重新启动。", "", "", "", "", "", 0},
  {"Searching on %s", "正在搜索 %s", "Recherche sur %s", "Suche auf %s", "", "Поиск по %s", "Buscando en %s", 0},
  {"Radio Uplink %d", "上行链路 %d", "", "", "", "", "", 0},
  {"Controller Radio Interface %d Settings", "遥控器通道 %d 参数", "", "", "", "", "", 0},
  {"Your radio interface (%s) has multiple cloned variants manufactured. Tx power varies depending on clone manufacturer, so a certain value can't be established.", "您的遥控器射频模块(%s)存在多个版本，不同厂商生产的无线模块间功率数值存在差异，因此无法设定固定参数值", "", "", "", "", "", 0},
  {"Some of your radio interfaces (%s) have multiple cloned variants manufactured. Tx power varies depending on clone manufacturer, so a certain value can't be established.", "您使用的部分射频模块(%s)存在多个版本，由于不同厂商生产的无线模块的发射功率参数不一致，因此无法设定标准数值", "", "", "", "", "", 0},
  {"Radio Link %d Frequency", "无线链路%d频率", "", "", "", "", "", 0},
  {"Radio Link %d Data Rate", "无线链路%d数据速率", "", "", "", "", "", 0},
  {"Radio Link %d Tx Power (mw)", "无线链路%d发射功率 (mw)", "", "", "", "", "", 0},
  {"Current real display resolution: %dx%d", "当前实际显示分辨率：%dx%d", "", "", "", "", "", 0},
  {"Max FPS for this video mode (%d x %d) for this camera is %d FPS", "在当前视频模式下(%d x %d)摄像头的最大帧率 %d FPS", "", "", "", "", "", 0},
  {"Are you sure you want to delete %s?", "你确定要删除%s吗？", "", "", "", "", "", 0},
  {"Current camera sensor changed from %s to %s", "当前摄像头传感器已从 %s 更改为 %s", "", "", "", "", "", 0},
  {"%s has Ruby version %s (b%u) and your controller %s (b%u). You should update your %s.", "%s 的 Ruby 版本为 %s（b%u），而您的地面端 %s 版本为 %s（b%u）。建议立即升级 %s 。", "", "", "", "", "", 0},
  {"Some radio interfaces on your %s are not fully supported.", "您的设备 %s 上存在部分不完全兼容的射频模块", "", "", "", "", "", 0},
  {"No radio interface on your %s is fully supported.", "您的设备 %s 完全不支持当前射频模块", "", "", "", "", "", 0},
  {"Radio links configuration changed on your %s. Updating local radio configuration...", "您的设备 %s 的无线链路配置已变更，正在更新本地射频参数...", "", "", "", "", "", 0},
  {"Looking for default vehicle on %s frequency...", "正在 %s 频段上扫描默认天空端信号...", "", "", "", "", "", 0},
  {"Looking for %s (%s, %s)...", "扫描 %s (%s, %s)...", "", "", "", "", "", 0},
  {"Looking for %s (%s, %s / %s)...", "扫描 %s (%s, %s / %s)...", "", "", "", "", "", 0},
  {"Warning: There is a different vehicle (%s) on the same frequency as your current vehicle (%s)!", "警告：当前频段存在另一设备 (%s) 与您的设备 (%s) 冲突！", "", "", "", "", "", 0},
  {"Warning: There is a different vehicle (%s) on the same frequency (%s) as your current vehicle (%s)!", "警告：存在另一台设备(%s)在当前频段(%s)与您的设备(%s)冲突！", "", "", "", "", "", 0},
  {"Warning: There is a different vehicle (%s) on the same frequencies (%s/%s) as your current vehicle (%s)!", "警告：警告：存在另一台设备(%s)在当前双频段(%s/%s)与您的设备(%s)冲突！", "", "", "", "", "", 0},
  {"Data stream from vehicle lost (%u)!", "设备数据流中断！(%u)", "", "", "", "", "", 0},
  {"Data stream from vehicle recovered (%u)", "设备数据流恢复！(%u)", "", "", "", "", "", 0},
  {"Fatal error: Invalid model! (code: %x)", "致命错误：无效的模型！(code: %x)", "", "", "", "", "", 0},
  {"You are sending too much data (%d Mbps) over the radio link (max capacity %d Mbps). Lower your video bitrate or increase your radio data rate.", "无线链路数据超载（当前：%d Mbps / 最大容量：%d Mbps）。请降低视频码率或提升无线数据速率。", "", "", "", "", "", 0},
  {"Switching to vehicle radio link %d (%s)", "切换设备至无线链路%d (%s)", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},


  //-------------------------------------------------------
  // Root menu
  
  {"Quick vehicle setup", "快速设置", "Configuration rapide", "Schnelle einrichtung", "", "Быстрая настройка", "Configuración rápida", 0},
  {"Quickly change the most common vehicle settings.", 
      "快速更改常用天空端设置。",
      "Modifiez rapidement les paramètres les plus courants du véhicule.", 
      "Ändern Sie schnell die gängigsten Fahrzeugeinstellungen.",
      "",
      "Быстро меняйте наиболее распространенные настройки автомобиля.",
      "Cambie rápidamente las configuraciones más comunes del vehículo.", 0},
  {"Search", "搜索", "Recherche", "Suchen", "", "Поиск", "Buscar", 0},
  {"Search for vehicles.", "搜索天空端。", "Rechercher des véhicules.", "Suche nach Fahrzeugen.", "", "Поиск транспортных средств.", "Búsqueda de vehículos.", 0},
  {"My vehicles", "我的天空端", "Mes véhicules", "Meine Fahrzeuge", "", "Мои транспортные средства", "Mis vehículos", 0},
  {"Manage my vehicles.", "管理我的天空端。", "Gérer mes véhicules.", "Meine Fahrzeuge verwalten.", "", "Управляйте моими транспортными средствами.", "Administrar mis vehículos.", 0},
  {"Vehicle settings", "天空端设置", "Paramètres du véhicule", "Fahrzeugeinstellungen", "", "Настройки автомобиля", "Configuración del vehículo", 0},
  {"Change vehicle settings.", "更改天空端设置。", "Modifier les paramètres du véhicule.", "Fahrzeugeinstellungen ändern.", "", "Измените настройки автомобиля.", "Cambiar la configuración del vehículo.", 0},
  {"Controller settings", "地面端设置", "Paramètres du contrôleur", "Controller-Einstellungen", "", "Настройки контроллера", "Configuración del controlador", 0},
  {"Change controller settings and user interface preferences.",
       "更改地面端设置和用户界面首选项。",
       "Modifiez les paramètres du contrôleur et les préférences de l'interface utilisateur.",
       "Ändern Sie die Controllereinstellungen und Benutzeroberflächeneinstellungen.",
       "",
       "Измените настройки контроллера и предпочтения пользовательского интерфейса.",
       "Cambiar la configuración del controlador y las preferencias de la interfaz de usuario.", 0},
  {"System", "系统", "Système", "System", "", "Система", "Sistema", 0},
  {"Configure system options, shows detailed information about the system.",
      "配置系统选项，显示有关系统的详细信息。", 
      "Configurer les options du système, affiche des informations détaillées sur le système.",
      "Konfigurieren Sie die Systemoptionen. Zeigt detaillierte Informationen zum System an.",
      "",
      "Настройка параметров системы, отображение подробной информации о системе.",
      "Configurar opciones del sistema, muestra información detallada sobre el sistema.", 0},
  {"Media & storage", "媒体和存储", "Médias et stockage", "Medien und Speicher", "", "Медиа и хранение", "Medios y almacenamiento", 0},
  {"Manage saved logs, screenshots and videos.", "管理已保存的日志、屏幕截图和视频。", "Gérez les journaux enregistrés, les captures d'écran et les vidéos.", "Verwalten Sie gespeicherte Protokolle, Screenshots und Videos.", "", "Управляйте сохраненными журналами, снимками экрана и видео.", "Administrar registros, capturas de pantalla y vídeos guardados.", 0},
  {"Not paired with any vehicle", "未与任何天空端配对", "Non jumelé à aucun véhicule", "Nicht mit einem Fahrzeug gekoppelt", "", "Не сопряжено ни с одним транспортным средством", "No emparejada con ningún vehículo", 0},
  {"Search for a vehicle to find one and connect to or select one from your paired vehicles.", "搜索天空端以连接，或从已配对的天空端中选择", "", "", "", "", "", 0},
  {"Spectator mode", "观众模式", "Mode spectateur", "Zuschauermodus", "", "Режим наблюдателя", "Modo espectador", 0},
  {"Full control mode", "完全控制模式", "Mode contrôle total", "Vollzugriffsmodus", "", "Режим полного контроля", "Modo de control total", 0},
  {"flights", "飞行", "vols", "Flüge", "", "полеты", "vuelos", 0},
  {"flight time", "飞行时间", "temps de vol", "Flugzeit", "", "время полета", "tiempo de vuelo", 0},
  {"Not paired with any vehicle", "未与任何天空端配对", "Non jumelé à aucun véhicule", "Nicht mit einem Fahrzeug gekoppelt", "", "Не сопряжено ни с одним транспортным средством", "No emparejada con ningún vehículo", 0},
  {"Search for a vehicle to find one and connect to or select one of your paired vehicles.",
      "搜索天空端以连接，或从已配对的天空端中选择",
      "Recherchez un véhicule pour en trouver un et connectez-vous ou sélectionnez l'un de vos véhicules jumelés.",
      "Suchen Sie nach einem Fahrzeug, um eines zu finden und eine Verbindung herzustellen oder eines Ihrer gekoppelten Fahrzeuge auszuwählen.",
      "",
      "Найдите транспортное средство, подключитесь к нему или выберите одно из сопряженных транспортных средств.",
      "Busque un vehículo para encontrar uno y conectarse o seleccionar uno de sus vehículos emparejados.", 0},

  //----------------------------------------------------------------------
  // Controller Menu
  
  {"Audio & Video Output", "音频 & 视频输出", "", "", "", "", "", 0},
  {"Telemetry Input/Output", "遥测输入/输出", "", "", "", "", "", 0},
  {"Radio", "无线电链路", "", "", "", "", "", 0},
  {"CPU and Processes", "CPU和进程", "", "", "", "", "", 0},
  {"Peripherals & Ports", "外围设备和端口", "", "", "", "", "", 0},
  {"Local Network Settings", "本地网络设置", "", "", "", "", "", 0},
  {"Buttons", "按键", "", "", "", "", "", 0},
  {"User Interface", "用户界面", "Interface utilisateur", "", "", "", "", 0},
  {"Change user interface preferences: language, fonts, colors, sizes, display units.",
      "更改用户界面偏好：语言、字体、颜色、大小、显示单位。",
      "", "", "", "", "", 0},
  {"Recording Settings", "录制设置", "", "", "", "", "", 0},
  {"Management", "管理", "", "", "", "", "", 0},
  {"Manage Plugins", "插件管理", "", "", "", "", "", 0},
  {"Update Software", "更新软件", "", "", "", "", "", 0},
  {"Restart Controller", "重启地面端", "", "", "", "", "", 0},

  //---------------------------------------------------------------------
  // Controller User Interface menu
  
  {"Controller User Interface", "地面端用户界面", "Interface utilisateur du contrôleur", "Controller-Benutzeroberfläche", "", "Пользовательский интерфейс контроллера", "Interfaz de usuario del controlador", 0},
  {"Menus", "菜单", "", "", "मेनू", "Меню", "", 0},
  {"Menus layout", "菜单布局", "", "", "", "Макет меню", "", 0},
  {"Changes how the menus appear on screen.", "更改菜单在屏幕上的显示方式", "", "", "", "Изменяет внешний вид меню на экране.", "", 0},
  {"Menu font size", "菜单字体大小", "", "", "मेनू फ़ॉन्ट आकार", "Размер шрифта меню", "", 0},
  {"Change how big the menus appear on screen.", "更改屏幕上菜单的显示大小。", "", "", "स्क्रीन पर मेनू कितना बड़ा दिखाई देगा, इसे बदलें.", "Измените размер меню на экране.", "", 0},
  {"Invert colors", "反转颜色", "", "", "रंग उलटें", "Инвертировать цвета", "", 0},
  {"Invert colors on OSD and menus.", "反转 OSD 和菜单的颜色。", "", "", "OSD और मेनू पर रंग उलटें।", "Инвертируйте цвета в OSD и меню.", "", 0},
  {"OSD text color", "OSD文本颜色", "", "", "OSD पाठ रंग", "Цвет текста OSD", "", 0},
  {"Change color of the text in the OSD.", "更改 OSD 中文本的颜色。", "", "", "OSD में पाठ का रंग बदलें।", "Измените цвет текста в OSD.", "", 0},
  {"OSD outline color", "OSD 轮廓颜色", "", "", "OSD रूपरेखा रंग", "Цвет контура OSD", "", 0},
  {"Change color of the outline in the OSD.", "改变 OSD 中的轮廓颜色。", "", "", "", "Измените цвет контура в OSD.", "", 0},
  {"OSD outline thickness", "OSD 轮廓厚度", "", "", "", "Толщина контура OSD", "", 0},
  {"Increase/decrease OSD outline thickness.", "增加/减少 OSD 轮廓粗细。", "", "", "", "Увеличить/уменьшить толщину контура OSD.", "", 0},
  {"OSD screen size", "OSD 屏幕尺寸", "", "", "", "Размер экрана OSD", "", 0},
  {"Change how big is the OSD relative to the screen.", "更改 OSD 相对于屏幕的大小。", "", "", "", "Измените размер OSD относительно экрана.", "", 0},
  {"OSD flip vertical", "OSD 垂直翻转", "", "", "", "Перевернуть OSD по вертикали", "", 0},
  {"Flips the OSD info vertically for rotated displays.", "垂直翻转 OSD 信息以适应旋转的显示。", "", "", "", "Переворачивает информацию OSD по вертикали для повернутых дисплеев.", "", 0},
  {"Instruments color", "仪表颜色", "", "", "", "Цвет инструментов", "", 0},
  {"Change color of the instruments/gauges.", "改变仪器/仪表的颜色。", "", "", "", "Изменение цвета приборов/датчиков.", "", 0},
  {"Ruby OSD font", "Ruby OSD 字体", "", "", "", "Шрифт OSD Ruby", "", 0},
  {"Changes the OSD font used for Ruby OSD elements.", "更改Ruby OSD元素的OSD字体。", "", "", "", "", "", 0},
  {"OSD font", "OSD 字体", "", "", "", "Шрифт OSD", "", 0},
  {"Changes the OSD font.", "更改OSD字体", "", "", "", "", "", 0},
  {"Ruby OSD font style", "Ruby OSD 字体样式", "", "", "", "Стиль шрифта OSD Ruby", "", 0},
  {"Changes the OSD font style used for Ruby OSD elements.", "", "", "", "", "", "", 0},
  {"OSD font style", "OSD 字体样式", "", "", "", "Стиль шрифта OSD", "", 0},
  {"Changes the OSD font style.", "更改OSD字体样式", "", "", "", "", "", 0},
  {"MSP OSD font", "MSP OSD 字体", "", "", "", "Шрифт OSD MSP", "", 0},
  {"Changes the OSD font used for MSP OSD.", "更改 MSP OSD 的字体。", "", "", "", "", "", 0},
  {"Side by side", "并排", "", "", "", "Бок о бок", "", 0},
  {"Stacked", "堆叠", "", "", "", "Сложенный", "", 0},
  {"Sticky Left", "左侧吸附", "", "", "", "Прикрепленный левый", "", 0},
  {"Inverted", "Inverted", "", "", "", "Перевернутый", "", 0},
  {"None", "None", "", "", "कोई नहीं", "Никто", "", 0},
  {"X-Small", "X-Small", "", "", "", "X-маленький", "", 0},
  {"Smallest", "Smallest", "", "", "सबसे छोटा", "Самый маленький", "", 0},
  {"Smaller", "Smaller", "", "", "", "Меньше", "Mas pequeño", 0},
  {"Small", "Small", "", "", "छोटा", "Маленький", "", 0},
  {"Normal", "Normal", "", "", "सामान्य", "Нормальный", "", 0},
  {"Large", "Large", "", "", "बड़ा", "Большой", "", 0},
  {"Larger", "Larger", "", "", "बड़ा", "Больше", "", 0},
  {"Largest", "Largest", "", "", "सबसे बड़ा", "Самый большой", "", 0},
  {"X-Large", "X-Large", "", "", "", "Очень большой", "", 0},

  {"General", "常规", "", "", "सामान्य", "Общий", "", 0},
  {"Language", "语言", "Langue", "Sprache", "भाषा", "Язык", "Idioma", 0},
  {"Change the user interface language.", "更改用户界面语言。", "Changer la langue de l'interface utilisateur.", "Ändern Sie die Sprache der Benutzeroberfläche.", "उपयोगकर्ता इंटरफ़ेस भाषा बदलें.", "Измените язык пользовательского интерфейса.", "Cambiar el idioma de la interfaz de usuario.", 0},
  {"Display units", "显示单位", "", "", "", "Дисплейные блоки", "", 0},
  {"Changes how the OSD displays data: in metric system or imperial system.", "更改OSD数据显示单位：公制或英制", "", "", "", "", "", 0},
  {"Display units (Heights)", "显示单位（高度）", "", "", "", "Единицы отображения (высоты)", "", 0},
  {"Changes how the OSD displays heights: in metric system or imperial system.", "更改OSD高度显示单位：公制或英制", "", "", "", "", "", 0},
  {"Persist messages longer", "延长消息显示时间", "", "", "", "Сохранять сообщения дольше", "", 0},
  {"Keep the various messages and warnings longer on the screen.", "延长各类消息和警告在屏幕上的显示时间", "", "", "", "", "", 0},
  {"Log messages window", "日志消息窗口", "", "", "", "Окно сообщений журнала", "", 0},
  {"Shows the log messages window.", "显示日志消息窗口", "", "", "", "", "", 0},
  {"Bold", "Bold", "", "", "", "Смелый", "", 0},
  {"Regular", "Regular", "", "", "", "Обычный", "", 0},
  {"On New Content", "有新消息时", "", "", "", "", "", 0},
  {"Always On", "始终开启", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},

  //------------------------------------------------------------
  // Menu vehicle simple setup


  {"First time pairing setup:", "首次配对设置:", "", "", "", "", "", 0},
  {"(You can later change the values again from menus)", "(后续可通过菜单重新调整参数)", "", "", "", "", "", 0},
  {"Missing vehicle configuration.", "设备配置丢失", "", "", "", "", "", 0},
  {"Closes this settings.", "关闭当前设置", "", "", "", "", "", 0},
  {"Camera settings", "摄像头设置", "", "", "", "", "", 0},
  {"Change camera settings: brightness, constrast, saturation, hue, etc.", "调整摄像头参数：亮度、对比度、饱和度、色调等", "", "", "", "", "", 0},
  {"Video settings", "视频设置", "", "", "", "", "", 0},
  {"Change video settings: resolution, FPS, bitrate, etc.", "调整视频参数：分辨率、帧率、码率等", "", "", "", "", "", 0},
  {"Select the OSD layout you want, how many OSD elements to show by default on your screen:", "选择OSD布局及默认显示元素数量:", "", "", "", "", "", 0},
  {"OSD Layout", "OSD布局", "", "", "", "", "", 0},
  {"Set the default layout of this OSD screen (what elements are shown on this screen).", "设置当前OSD屏幕的默认布局（显示元素配置）", "", "", "", "", "", 0},
  {"Minimal", "极简模式", "", "", "", "", "", 0},
  {"Compact", "紧凑模式", "", "", "", "", "", 0},
  {"If you have a flight controller, select the telemetry type used by the flight controller:", "若已安装飞控，请选择其使用的遥测类型:", "", "", "", "", "", 0},
  {"FC Telemetry Type", "飞控遥测类型", "", "", "", "", "", 0},
  {"The telemetry type that is sent/received from the flight controller. This should match the telemetry type generated by the flight controller.", "飞控收发使用的遥测协议类型，需与飞控生成的遥测类型匹配", "", "", "", "", "", 0},
  {"If you have a flight controller, select the air unit's serial port the flight controller is connected to:", "若已安装飞控，请选择其连接至天空端的串口:", "", "", "", "", "", 0},
  {"Telemetry Port", "遥测端口", "", "", "", "", "", 0},
  {"The Ruby vehicle port at which the flight controller telemetry connects to.", "连接飞控遥测的Ruby天空端端口", "", "", "", "", "", 0},
  {"Looks Good! Done", "配置完成", "", "", "", "", "", 0},
  {"Applies the selections and closes this settings page.", "应用当前选择并关闭设置页面", "", "", "", "", "", 0},
  {"Full Vehicle Settings", "完整参数设置", "", "", "", "", "", 0},
  {"Configure/change all vehicle settings.", "配置/修改所有设备参数", "", "", "", "", "", 0},
  {"Sets the radio link frequency for this radio link.", "设置当前无线链路频率", "", "", "", "", "", 0},
  {"Change the radio link frequency.", "更改无线链路频率", "", "", "", "", "", 0},
  {"Please wait", "请稍候", "", "", "", "", "", 0},
  {"Autodetecting telemetry settings", "正在自动检测遥测设置", "", "", "", "", "", 0},
  {"User Data Link Disabled", "用户数据链路已禁用", "", "", "", "", "", 0},
  {"The serial port was used by your custom data link. It was reasigned to the telemetry link.", "该串口已被自定义数据链路占用，现已重新分配至遥测链路", "", "", "", "", "", 0},
  {"Not paired with any vehicle.", "未配对任何天空端", "", "", "", "", "", 0},
  {"Search for vehicles to find one and connect to.", "搜索可连接的天空端", "", "", "", "", "", 0},
  {"Configuration In Progress", "配置进行中", "", "", "", "", "", 0},
  {"Another radio link configuration change is in progress. Please wait.", "另一无线链路配置正在修改，请稍后", "", "", "", "", "", 0},
  {"Invalid option", "无效选项", "", "", "", "", "", 0},
  {"Confirmation", "确认", "", "", "", "", "", 0},
  {"Can't update radio links", "无法更新无线链路", "", "", "", "", "", 0},
  {"You need to update your vehicle to version 9.2 or newer", "需将设备固件升级至9.2或更新版本", "", "", "", "", "", 0},


  //-----------------------------------------------------
  // Menus confirmations

  {"Update Info", "更新信息", "", "", "", "", "", 0},
  {"Unsuppoerted video codec", "不支持的视频编解码", "", "", "", "", "", 0},
  {"Unsuppoerted video slices", "不支持的视频分片", "", "", "", "", "", 0},
  {"Hardware Info", "硬件信息", "", "", "", "", "", 0},
  {"Do not show again", "不再显示", "", "", "", "", "", 0},
  {"Delete vehicle logs", "删除天空端日志", "", "", "", "", "", 0},
  {"Do you want to delete the logs?", "确认删除日志？", "", "", "", "", "", 0},
  {"(If you don't select anything, it will auto revert to old HDMI configuration after a timeout)", "(未选择将超时恢复原有HDMI配置)", "", "", "", "", "", 0},
  {"Failed to import settings from USB memory stick.", "无法从USB导入设置 ", "", "", "", "", "", 0},
  {"A Ruby update is present on the SD card.", "检测到SD卡上的Ruby更新包", "", "", "", "", "", 0},
  {"Do you want to update Ruby from the SD card?", "确认从SD卡更新Ruby系统？", "", "", "", "", "", 0},
  {"Your controller will reboot now.", "地面端即将重启", "", "", "", "", "", 0},
  {"Failed to do the SD card update.", "SD卡更新失败", "", "", "", "", "", 0},
  {"Doing the SD card update. Please wait...", "正在执行SD卡更新，请稍候...", "", "", "", "", "", 0},
  {"(You can later change it from vehicle menu)", "(后续可通过天空端菜单修改)", "", "", "", "", "", 0},
  {"Select your vehicle board type", "选择天空端主板类型", "", "", "", "", "", 0},
  {"Update from SD card", "从SD卡更新", "", "", "", "", "", 0},
  {"Video Bitrate Adjustment", "视频码率调整", "", "", "", "", "", 0},
  {"Update Controller Software", "更新地面端软件", "", "", "", "", "", 0},
  {"Insert an USB stick containing the Ruby update archive file and then press Ok to start the update process.", "插入含Ruby更新包的U盘后点击确定开始更新", "", "", "", "", "", 0},
  {"Warning! Reboot Confirmation", "警告！重启确认", "", "", "", "", "", 0},
  {"Warning: You have the RC link enabled, the vehicle flight controller might not go into failsafe mode during reboot.", "警告：遥控链路启用时重启，飞控可能不会进入失控保护", "", "", "", "", "", 0},
  {"Updating. Please wait...", "更新中，请稍候...", "", "", "", "", "", 0},
  {"No USB memory stick detected. Please insert a USB stick.", "未检测到U盘，请插入", "", "", "", "", "", 0},
  {"USB memory stick detected but could not be mounted. Please try again.", "U盘挂载失败，请重试", "", "", "", "", "", 0},
  {"Update Failed", "更新失败", "", "", "", "", "", 0},
  {"Update timedout and failed.", "更新超时失败", "", "", "", "", "", 0},
  {"Update Info", "更新信息", "", "", "", "", "", 0},
  {"No update archive file found on the USB memory stick. No update done.", "U盘内未找到更新包", "", "", "", "", "", 0},
  {"Update Complete", "更新完成", "", "", "", "", "", 0},
  {"Update complete. You can now remove the USB stick. The system will reboot now.", "更新完成，可移除U盘，系统即将重启", "", "", "", "", "", 0},
  {"(If it does not reboot, you can power it off and on)", "(未自动重启可手动断电)", "", "", "", "", "", 0},
  {"Your vehicle is armed, you can't perform this operation now. Please stop/disarm your vehicle first.", "设备已解锁，请先停转/上锁再操作", "", "", "", "", "", 0},
  {"Update was canceled.", "更新已取消", "", "", "", "", "", 0},
  {"There was an error generating software upload file.", "生成上传文件出错", "", "", "", "", "", 0},
  {"There was an error generating upload software archive.", "创建更新包出错", "", "", "", "", "", 0},
  {"Vehicle update binary files are missing or update procedure changed. Please update (again) your controller.", "缺失天空端更新文件，请先更新遥控器", "", "", "", "", "", 0},
  {"There was an error updating your vehicle.", "天空端更新出错", "", "", "", "", "", 0},
  {"Sets the radio interface model.", "设置射频模块型号", "", "", "", "", "", 0},
  {"Sets the radio Tx power level.", "设置射频发射功率", "", "", "", "", "", 0},
  {"There was an error generating the software package.", "生成软件包出错", "", "", "", "", "", 0},
  {"There was an error uploading the software package.", "上传软件包出错", "", "", "", "", "", 0},
  {"Not connected", "未连接", "", "", "", "", "", 0},
  {"Video Bitrate Warning", "视频码率警告", "", "", "", "", "", 0},
  {"Functionality not supported", "功能不支持", "", "", "", "", "", 0},
  {"Can't update", "无法更新", "", "", "", "", "", 0},
  {"This vehicle does not support OTA (over the air) updates.", "该天空端不支持OTA无线更新", "", "", "", "", "", 0},
  {"Upgrade Confirmation", "确认升级", "", "", "", "", "", 0},
  {"Confirmation", "确认", "", "", "", "", "", 0},
  {"You will need to search and pair with the vehicle again after that.", "完成后需重新搜索配对天空端", "", "", "", "", "", 0},
  {"Warning! Reboot Confirmation", "警告！重启确认", "", "", "", "", "", 0},
  {"Warning: You have the RC link enabled, the vehicle flight controller will go into RC failsafe mode during reboot.", "警告：遥控链路启用时重启，飞控将进入遥控失控保护", "", "", "", "", "", 0},
  {"Upload Succeeded", "上传成功", "", "", "", "", "", 0},
  {"Reset Complete", "重置完成", "", "", "", "", "", 0},
  {"Your vehicle was reseted to default settings. It will reboot now.", "天空端已恢复出厂设置，即将重启", "", "", "", "", "", 0},
  {"Vehicle is offline", "天空端离线", "", "", "", "", "", 0},
  {"Vehicle settings can not be changed on a spectator vehicle.", "观众模式下无法修改天空端设置", "", "", "", "", "", 0},
  {"You need to update your vehicle sowftware to be able to use core plugins.", "需先更新天空端软件以使用核心插件", "", "", "", "", "", 0},
  {"Please insert a USB memory stick.", "请插入U盘", "", "", "", "", "", 0},
  {"USB memory stick invalid. Please try again.", "U盘无效，请重试", "", "", "", "", "", 0},
  {"Export Succeeded", "导出成功", "", "", "", "", "", 0},
  {"Your vehicle settings have been stored to the USB stick. You can now remove the USB stick.", "天空端设置已保存至U盘，可安全移除", "", "", "", "", "", 0},
  {"Info", "提示", "", "", "", "", "", 0},
  {"You have no vehicles. Search and connect to a vehicle first.", "未连接天空端，请先搜索配对", "", "", "", "", "", 0},
  {"You are currently paired with a vehicle in spectator mode. You can not change any vehicle settings while in spectator mode.", "当前处于观众模式，无法修改天空端设置", "", "", "", "", "", 0},


  //------------------------------------------------------------------
  // Menu about
  {"About", "关于", "", "", "", "", "", 0},
  {"Ruby base version: ", "Ruby基础版本", "", "", "", "", "", 0},
  {"Ruby system developed by: Petru Soroaga", "Ruby系统，由Petru Soroaga开发", "", "", "", "", "", 0},
  {"For info on the licence terms, check the license.txt file.", "有关许可条款信息，请查看license.txt文件", "", "", "", "", "", 0},
  {"Close the menu.", "关闭菜单", "", "", "", "", "", 0},


  //----------------------------------------------------------------------
  // Menus Search
  {"Select Frequencies", "选择频段", "", "", "", "", "", 0},
  {"Select All", "全选", "", "", "", "", "", 0},
  {"Deselect All", "取消全选", "", "", "", "", "", 0},
  {"Search for vehicles", "搜索天空端", "", "", "", "", "", 0},
  {"Make sure your vehicle is powered on when you start searching.", "开始搜索前请确保天空端已上电", "", "", "", "", "", 0},
  {"Note: Long press on [Cancel] key or choose 'Stop Search' to cancel a search in progress.", "注：长按[取消]键或选择'停止搜索'可中断搜索", "", "", "", "", "", 0},
  {"Manual Search", "手动搜索", "", "", "", "", "", 0},
  {"Manualy search on a particular frequency", "在特定频率上手动搜索", "", "", "", "", "", 0},
  {"No supported frequencies", "无可用频段", "", "", "", "", "", 0},
  {"Band:", "频段:", "", "", "", "", "", 0},
  {"Change the frequency bands to search on.", "更改要搜索的频段范围", "", "", "", "", "", 0},
  {"No bands supported.", "无支持的频段", "", "", "", "", "", 0},
  {"Start Search", "开始搜索", "", "", "", "", "", 0},
  {"Start/Stop searching for vehicles on current band.", "开始/停止在当前频段搜索天空端", "", "", "", "", "", 0},
  {"SiK Radio Data Rate", "SiK无线电数据速率", "", "", "", "", "", 0},
  {"Sets the physical radio air data rate to use while searching.", "设置搜索时使用的空口数据速率", "", "", "", "", "", 0},
  {"Search for vehicles to connect to as spectator only:", "仅以观众模式搜索天空端:", "", "", "", "", "", 0},
  {"Note: Long press on [Cancel] or 'Stop Search' to cancel a search in progress.", "注：长按[取消]或'停止搜索'可中断进程", "", "", "", "", "", 0},
  {"None of your radio cards support this frequency band. Please choose another frequency band to search on.", "当前射频模块不支持该频段，请选择其他频段", "", "", "", "", "", 0},
  {"Stop Search", "停止搜索", "", "", "", "", "", 0},
  {"Start Search", "开始搜索", "", "", "", "", "", 0},
  {"No vehicles found!", "未发现天空端！", "", "", "", "", "", 0},
  {"Vehicle found and skipped.", "已发现但跳过该天空端", "", "", "", "", "", 0},
  {"You could search on other bands and channels.", "可尝试在其他频段/频道搜索", "", "", "", "", "", 0},
  {"Searching..", "搜索中..", "", "", "", "", "", 0},
  {"No active radio interfaces.", "无可用射频接口", "", "", "", "", "", 0},
  {"All your controller's radio interfaces are disabled. Enable at least a radio interface (from the Radio menu) to be able to search for vehicles.", "所有射频接口已禁用，请至少启用一个接口（通过射频菜单）", "", "", "", "", "", 0},
  {"Searching ...", "搜索中 ...", "", "", "", "", "", 0},
  {"Long press on [Back] to stop the search.", "长按[返回]键停止搜索", "", "", "", "", "", 0},
  {"Found Vehicle", "发现天空端", "", "", "", "", "", 0},
  {"Connect for control", "连接以进行控制", "", "", "", "", "", 0},
  {"Connect to this vehicle as controller", "连接并控制该天空端", "", "", "", "", "", 0},
  {"View as spectator", "观众模式", "", "", "", "", "", 0},
  {"Connect to this vehicle as spectator", "以观众模式连接", "", "", "", "", "", 0},
  {"Skip", "跳过", "", "", "", "", "", 0},
  {"Skip this vehicle", "跳过此天空端", "", "", "", "", "", 0},
  {"Can't get vehicle info", "无法获取天空端信息", "", "", "", "", "", 0},

  //-----------------------------------------------------------
  // Menus


  {"CPU and Processes Settings", "CPU与进程设置", "", "", "", "", "", 0},
  {"Enable CPU Overclocking", "启用CPU超频", "", "", "", "", "", 0},
  {"Enables overclocking of the main CPU.", "启用主CPU超频功能", "", "", "", "", "", 0},
  {"Modules versions", "模块版本", "", "", "", "", "", 0},
  {"Get all modules versions.", "获取所有模块版本信息", "", "", "", "", "", 0},
  {"Reset Priorities", "重置优先级", "", "", "", "", "", 0},
  {"Resets all controller priorities.", "重置所有控制器优先级", "", "", "", "", "", 0},
  {"Restart", "重启", "", "", "", "", "", 0},
  {"Restarts the controller.", "重启控制器", "", "", "", "", "", 0},
  {"Color Picker", "颜色选择器", "", "", "", "", "", 0},
  {"Initial Auto Radio Link Adjustment", "无线链路初始自动调参", "", "", "", "", "", 0},
  {"Doing the initial radio link parameters adjustment for best performance...", "正在执行无线链路参数初始调参以获得最佳性能...", "", "", "", "", "", 0},
  {"(This is done on first installation and on first pairing with a vehicle or when hardware has changed on the vehicle)", "(此操作在首次安装、首次配对天空端或天空端硬件变更时执行)", "", "", "", "", "", 0},
  {"Please wait, it will take a minute (you can press [Cancel] to cancel).", "请稍候，约需1分钟(可按[取消]中断)", "", "", "", "", "", 0},
  {"Computing Link Quality", "计算链路质量", "", "", "", "", "", 0},
  {"Done. Sending message to vehicle to save parameters.", "完成。正在向天空端发送参数保存指令", "", "", "", "", "", 0},
  {"Canceling, please wait.", "正在取消，请稍候", "", "", "", "", "", 0},
  {"Testing modulation schemes parameters", "测试调制方案参数", "", "", "", "", "", 0},
  {"Aborts the autoadjustment procedure without making any changes.", "中止自动调参且不保存任何更改", "", "", "", "", "", 0},
  {"Failed to negociate radio links.", "无线链路协商失败", "", "", "", "", "", 0},
  {"You radio links quality is very poor. Please fix the physical radio links quality and try again later.", "无线链路质量极差，请检查物理连接后重试", "", "", "", "", "", 0},
  {"Negociated radio links", "已协商无线链路", "", "", "", "", "", 0},
  {"Negociated radio links was canceled", "无线链路协商已取消", "", "", "", "", "", 0},
  {"Controller Radio Settings", "地面端无线设置", "", "", "", "", "", 0},
  {"Controller Tx Power Mode", "地面端发射功率模式", "", "", "", "", "", 0},
  {"Sets the radio transmission power mode selector for the controller side: custom fixed power or auto computed for each radio link based on vechile radio links tx powers.", "设置地面端发射功率模式：固定功率或根据天空端无线链路发射功率自动计算", "", "", "", "", "", 0},
  {"Fixed uplink Tx power", "固定上行发射功率", "", "", "", "", "", 0},
  {"Match current vehicle", "匹配当前天空端", "", "", "", "", "", 0},
  {"Full Radio Config", "完整无线配置", "", "", "", "", "", 0},
  {"Full radio configuration", "无线全局配置", "", "", "", "", "", 0},
  {"Controller Tx power is set to fixed values.", "地面端发射功率设置为固定值", "", "", "", "", "", 0},
  {"Mode", "模式", "", "", "", "", "", 0},
  {"Radio Tx Power (mW)", "无线发射功率(mW)", "", "", "", "", "", 0},
  {"Controller Tx power is computed automatically for each radio link based on vehicle's radio links Tx power and the Tx capabilities of the controller's radio interfaces.", "控制器发射功率将根据天空端无线链路发射功率及控制器射频接口能力自动计算", "", "", "", "", "", 0},
  {"No vehicle", "未连接天空端", "", "", "", "", "", 0},
  {"You are not connected to any vehicles. The Tx power is set automatically to a low value.", "未连接任何天空端，发射功率自动降低", "", "", "", "", "", 0},
  {"Radio Uplink", "无线上行链路", "", "", "", "", "", 0},
  {"Controller Radio Interface Settings", "地面端射频接口设置", "", "", "", "", "", 0},
  {"No radio interfaces detected on the system!", "未检测到系统射频接口！", "", "", "", "", "", 0},
  {"Card Model", "模块型号", "", "", "", "", "", 0},
  {"Enables or disables this card.", "启用/禁用此模块", "", "", "", "", "", 0},
  {"Preferred Uplink Card", "首选上行模块", "", "", "", "", "", 0},
  {"Sets this card as preffered one for uplink.", "设置此模块为上行链路首选", "", "", "", "", "", 0},
  {"You have a single radio interface on this controller. You can not change it's main functionality.", "地面端仅有一个射频接口，无法更改其主要功能", "", "", "", "", "", 0},
  {"Capabilities", "功能模式", "", "", "", "", "", 0},
  {"Sets the uplink/downlink capabilities of the card. If the card has attached an external LNA or a unidirectional booster, it can't be used for both uplink and downlink, so it must be marked to be used only for uplink or downlink accordingly.", "设置模块的上行/下行功能。若模块连接了外部LNA或单向放大器，则必须相应设置为仅上行或仅下行", "", "", "", "", "", 0},
  {"Uplink & Downlink", "上行/下行", "", "", "", "", "", 0},
  {"Downlink Only", "仅下行", "", "", "", "", "", 0},
  {"Uplink Only", "仅上行", "", "", "", "", "", 0},
  {"Card Location", "模块位置", "", "", "", "", "", 0},
  {"Marks this card as internal or external.", "标记此模块为内置或外置", "", "", "", "", "", 0},
  {"External", "外置", "", "", "", "", "", 0},
  {"Internal", "内置", "", "", "", "", "", 0},
  {"Custom Name", "自定义名称", "", "", "", "", "", 0},
  {"Sets a custom name for this unique physical radio interface; This name is to be displayed in the OSD and menus, to easily identify and distinguish each physical radio interface from the others.", "为此物理射频接口设置自定义名称，该名称将显示在OSD和菜单中用于区分不同接口", "", "", "", "", "", 0},
  {"Updating Radio Configuration. Please wait...", "正在更新无线配置，请稍候...", "", "", "", "", "", 0},
  {"You can't disable all the radio interfaces!", "不能禁用所有射频接口！", "", "", "", "", "", 0},
  {"The selected value was updated.", "选定值已更新", "", "", "", "", "", 0},
  {"You can't disable the single active radio interface.", "不能禁用唯一活跃的射频接口", "", "", "", "", "", 0},
  {"Invalid option", "无效选项", "", "", "", "", "", 0},
  {"Can't set the interface as RX or TX only because it's the only active interface on the system.", "无法设置该接口为仅RX/TX模式，因为这是系统唯一的活跃接口", "", "", "", "", "", 0},
  {"Vehicle Settings", "天空端设置", "", "", "", "", "", 0},
  {"You are connected in spectator mode. Can't change vehicle settings.", "当前处于观众模式，无法修改天空端设置", "", "", "", "", "", 0},
  {"General", "常规设置", "", "", "", "", "", 0},
  {"Change general settings like name, type of vehicle and so on.", "修改名称、天空端类型等常规参数", "", "", "", "", "", 0},
  {"Radio Links", "无线链路", "", "", "", "", "", 0},
  {"Change the radio links configuration of this vehicle.", "修改本天空端的无线链路配置", "", "", "", "", "", 0},
  {"Warnings/Alarms", "警告/报警", "", "", "", "", "", 0},
  {"Change which alarms and warnings to enable/disable.", "启用/禁用各类报警功能", "", "", "", "", "", 0},
  {"OSD / Instruments", "OSD/仪表", "", "", "", "", "", 0},
  {"Change OSD type, layout and settings.", "修改OSD类型、布局及参数", "", "", "", "", "", 0},
  {"Camera", "摄像头", "", "", "", "", "", 0},
  {"Change camera parameters: brightness, contrast, sharpness and so on.", "调整亮度、对比度、锐度等摄像头参数", "", "", "", "", "", 0},
  {"Video", "视频", "", "", "", "", "", 0},
  {"Change video resolution, fps so on.", "修改分辨率、帧率等视频参数", "", "", "", "", "", 0},
  {"Audio", "音频", "", "", "", "", "", 0},
  {"Change the audio settings", "调整音频设置", "", "", "", "", "", 0},
  {"Telemetry", "遥测", "", "", "", "", "", 0},
  {"Change telemetry parameters between flight controller and ruby vehicle.", "修改飞控与Ruby天空端间的遥测参数", "", "", "", "", "", 0},
  {"Auxiliary Data Link", "辅助数据链路", "", "", "", "", "", 0},
  {"Create and configure a general purpose data link between the vehicle and the controller.", "创建并配置天空端与地面端的通用数据链路", "", "", "", "", "", 0},
  {"Remote Control", "遥控器", "", "", "", "", "", 0},
  {"Change your remote control type, channels, protocols and so on.", "修改遥控器类型、通道、协议等参数", "", "", "", "", "", 0},
  {"Functions and Triggers", "功能与触发器", "", "", "", "", "", 0},
  {"Configure special functions and triggers.", "配置特殊功能与触发条件", "", "", "", "", "", 0},
  {"Relaying", "中继模式", "", "", "", "", "", 0},
  {"Configure this vehicle as a relay.", "将本天空端配置为中继节点", "", "", "", "", "", 0},
  {"Peripherals", "外设", "", "", "", "", "", 0},
  {"Change vehicle's serial ports settings and other peripherals.", "修改串口等外设参数", "", "", "", "", "", 0},
  {"CPU Settings", "CPU设置", "", "", "", "", "", 0},
  {"Change CPU overclocking settings and processes priorities.", "调整CPU超频及进程优先级", "", "", "", "", "", 0},
  {"Management", "管理", "", "", "", "", "", 0},
  {"Updates, deletes, back-up, restore the vehicle data and firmware.", "更新、删除、备份天空端数据与固件", "", "", "", "", "", 0},
  {"Vehicle Settings", "天空端设置", "", "", "", "", "", 0},
  {"No hardware alarms.", "无硬件报警", "", "", "", "", "", 0},
  {"Connected to:", "已连接:", "", "", "", "", "", 0},
  {"Looking for:", "正在搜索:", "", "", "", "", "", 0},
  {"Vehicle is offline", "天空端离线", "", "", "", "", "", 0},
  {"Vehicle Settings can not be changed on a spectator vehicle.", "观众模式下无法修改天空端设置", "", "", "", "", "", 0},
  {"OSD functionality has changed. You need to update your vehicle sowftware.", "OSD功能已变更，需更新天空端固件", "", "", "", "", "", 0},
  {"You need to update your vehicle sowftware to be able to use this menu.", "需更新天空端软件才能使用此菜单", "", "", "", "", "", 0},
  {"Can't change settings when not connected to the vehicle.", "未连接天空端时不能修改设置", "", "", "", "", "", 0},
  {"Vehicle Settings not synched yet", "天空端设置未同步", "", "", "", "", "", 0},
  {"This vehicle has no cameras.", "该天空端未搭载摄像头", "", "", "", "", "", 0},
  {"You can't change camera settings for a spectator vehicle.", "观众模式下不能修改摄像头设置", "", "", "", "", "", 0},
  {"This vehicle has no cameras or video streams.", "该天空端无摄像头或视频流", "", "", "", "", "", 0},
  {"This vehicle doesn't have any audio capture device. Audio can't be used on this vehicle.", "该天空端无音频采集设备", "", "", "", "", "", 0},
  {"You need to update your vehicle sowftware to be able to use this menu.", "需更新天空端软件才能使用此菜单", "", "", "", "", "", 0},
  {"OSD functionality has changed. You need to update your vehicle sowftware.", "OSD功能已变更，需更新天空端软件", "", "", "", "", "", 0},
  {"No Suitable Hardware", "无兼容硬件", "", "", "", "", "", 0},
  {"You need at least two radio interfaces on the vehicle to be able to use the relay functionality.", "需至少两个射频接口才能启用中继功能", "", "", "", "", "", 0},
  {"General Vehicle Settings", "天空端常规设置", "", "", "", "", "", 0},
  {"Name", "名称", "", "", "", "", "", 0},
  {"Vehicle Type", "天空端类型", "", "", "", "", "", 0},
  {"Changes the vehicle type Ruby is using. Has impact on things like OSD elements, telemetry parsing.", "更改Ruby天空端类型，将影响OSD元素显示及遥测数据解析", "", "", "", "", "", 0},
  {"Generic", "通用类型", "", "", "", "", "", 0},
  {"Drone", "多旋翼", "", "", "", "", "", 0},
  {"Airplane", "固定翼", "", "", "", "", "", 0},
  {"Helicopter", "直升机", "", "", "", "", "", 0},
  {"Car", "车", "", "", "", "", "", 0},
  {"Boat", "船", "", "", "", "", "", 0},
  {"Robot", "机器人", "", "", "", "", "", 0},
  {"Board Type", "主板类型", "", "", "", "", "", 0},
  {"Sets the board type variant.", "设置主板类型", "", "", "", "", "", 0},
  {"Vehicle Radio Configuration", "天空端无线配置", "", "", "", "", "", 0},
  {"Variable Tx Power", "动态发射功率", "", "", "", "", "", 0},
  {"No radio interfaces detected on this vehicle!", "未检测到射频接口！", "", "", "", "", "", 0},
  {"Full Radio Config", "完整无线设置", "", "", "", "", "", 0},
  {"Full radio configuration", "无线全局参数设置", "", "", "", "", "", 0},
  {"Disable Uplinks", "禁用上行链路", "", "", "", "", "", 0},
  {"Disable all uplinks, makes the system a one way system. Except for initial pairing and synching and sending commands to the vehicle. No video retransmissions happen, adaptive video is also disabled.", "禁用所有上行链路，系统将转为单向传输（仅保留初始配对、同步及基础指令传输功能），视频回传与自适应视频流同时禁用", "", "", "", "", "", 0},
  {"Prioritize Uplink", "上行链路优先", "", "", "", "", "", 0},
  {"Prioritize Uplink data over Downlink data. Enable it when uplink data resilience and consistentcy is more important than downlink data.", "优先保障上行链路数据传输，当上行数据可靠性比下行数据更重要时启用", "", "", "", "", "", 0},
  {"Optmize Radio Links Wizard", "无线链路优化向导", "", "", "", "", "", 0},
  {"Runs a process to optimize radio links parameters.", "执行无线链路参数优化流程", "", "", "", "", "", 0},
  {"Sets the radio link frequency for this radio link.", "设置当前无线链路频率", "", "", "", "", "", 0},
  {"Radio Link Frequency", "无线链路频率", "", "", "", "", "", 0},
  {"Change the radio link frequency.", "更改无线链路频率", "", "", "", "", "", 0},
  {"Radio Link Data Rate", "无线链路数据速率", "", "", "", "", "", 0},
  {"Radio Link Tx Power (mW)", "无线链路发射功率(mW)", "", "", "", "", "", 0},
  {"Missing Pass Code", "验证码缺失", "", "", "", "", "", 0},
  {"Configuration In Progress", "配置进行中", "", "", "", "", "", 0},
  {"Another radio link configuration change is in progress. Please wait.", "另一无线链路配置正在修改，请稍等", "", "", "", "", "", 0},
  {"Invalid option", "无效选项", "", "", "", "", "", 0},
  {"Can't update radio links", "无法更新无线链路", "", "", "", "", "", 0},
  {"You must update your vehicle first.", "需先升级天空端固件", "", "", "", "", "", 0},
  {"CPU Speed (Mhz)", "CPU主频(MHz)", "", "", "", "", "", 0},
  {"Sets the main CPU frequency. Requires a reboot.", "设置主CPU频率（需重启生效）", "", "", "", "", "", 0},
  {"Enable GPU Overclocking", "启用GPU超频", "", "", "", "", "", 0},
  {"Enables overclocking of the GPU cores.", "启用GPU核心超频功能", "", "", "", "", "", 0},
  {"GPU Speed (Mhz)", "GPU频率(MHz)", "", "", "", "", "", 0},
  {"Sets the GPU frequency. Requires a reboot.", "设置GPU工作频率（需重启生效）", "", "", "", "", "", 0},
  {"Enable Overvoltage", "启用超压", "", "", "", "", "", 0},
  {"Enables overvotage on the CPU and GPU cores. You need to increase voltage as you increase speed.", "为CPU/GPU核心启用超压功能，需随频率提升同步增加电压", "", "", "", "", "", 0},
  {"Overvoltage (steps)", "超压档位", "", "", "", "", "", 0},
  {"Sets the overvoltage value, in 0.025V increments. Requires a reboot.", "以0.025V为步进设置超压值（需重启生效）", "", "", "", "", "", 0},
  {"Reset CPU Freq", "重置CPU频率", "", "", "", "", "", 0},
  {"Resets the controller CPU and GPU frequencies to default values.", "将地面端CPU/GPU频率恢复默认值", "", "", "", "", "", 0},
  {"Priorities", "优先级", "", "", "", "", "", 0},
  {"Enable CPU Cores Auto Adjustment", "启用CPU核心自动调频", "", "", "", "", "", 0},
  {"Automatically adjust the work load on each CPU core.", "自动分配各CPU核心负载", "", "", "", "", "", 0},
  {"Auto", "自动", "", "", "", "", "", 0},
  {"Manual", "手动", "", "", "", "", "", 0},
  {"Audio & Video Output Settings", "音频 & 视频输出设置", "Paramètres de sortie audio et vidéo", "", "", "", "", 0},
  {"HDMI Output", "HDMI输出", "Sortie HDMI", "", "", "", "", 0},
  {"HDMI output resolution", "HDMI输出分辨率", "", "", "", "", "", 0},
  {"Sets the HDMI resolution on the controller display.", "设置地面端HDMI显示屏的分辨率", "", "", "", "", "", 0},
  {"HDMI refresh rate", "HDMI刷新率", "", "", "", "", "", 0},
  {"Sets the HDMI refresh rate for the display.", "设置HDMI显示屏的刷新率", "", "", "", "", "", 0},
  {"HDMI Output Boost", "HDMI输出增强", "", "", "", "", "", 0},
  {"Sets the boost voltage level for the HDMI output.", "设置HDMI输出的增强电压等级", "", "", "", "", "", 0},
  {"HDMI Overscan", "HDMI过扫描", "", "", "", "", "", 0},
  {"Default overscan (margins) on HDMI output. Requires a reboot after changing this value.", "设置HDMI输出的默认过扫描边距（修改后需重启）", "", "", "", "", "", 0},
  {"HDMI Vertical Sync", "HDMI垂直同步", "", "", "", "", "", 0},
  {"Enable vertical sync renderging synchronization on the HDMI display.", "启用HDMI显示的垂直同步渲染", "", "", "", "", "", 0},
  {"Calibrate HDMI output", "HDMI输出校准", "", "", "", "", "", 0},
  {"Calibrate the colors, brightness and contrast on the controller display.", "校准地面端显示屏的色彩、亮度与对比度", "", "", "", "", "", 0},
  {"Other Video Outputs", "其他视频输出", "", "", "", "", "", 0},
  {"Video Forward To USB Device", "视频转发至USB设备", "", "", "", "", "", 0},
  {"Enables or disables forwarding of the video stream to an external device using a USB connection.", "启用通过USB连接向外部设备转发视频流", "", "", "", "", "", 0},
  {"Video Forward To Network", "视频转发至网络", "", "", "", "", "", 0},
  {"Enables or disables forwarding of the video stream to the local network using the ETH connection.", "启用通过ETH网口向本地网络转发视频流", "", "", "", "", "", 0},
  {"Audio Output", "音频输出", "", "", "", "", "", 0},
  {"Audio Output Volume", "音频输出音量", "", "", "", "", "", 0},
  {"Sets the audio output volume", "设置音频输出音量", "", "", "", "", "", 0},
  {"Audio Test", "音频测试", "", "", "", "", "", 0},
  {"Test local audio output on your HDMI display/output speakers.", "测试HDMI显示器/扬声器的本地音频输出", "", "", "", "", "", 0},
  {"Changing HDMI resolution", "正在更改HDMI分辨率", "", "", "", "", "", 0},
  {"Your display will flicker or go black for few seconds while the HDMI mode is changed.", "切换HDMI模式时显示器可能出现闪烁或短暂黑屏", "", "", "", "", "", 0},
  {"Your device does not have audio output capabilities. Can't play audio.", "当前设备不支持音频输出功能", "", "", "", "", "", 0},
  {"Failed to test audio.", "音频测试失败", "", "", "", "", "", 0},
  {"This tests your HDMI display/output audio speakers. Now you should hear an audio sample.", "正在测试HDMI显示器/扬声器，您应该听到测试音频", "", "", "", "", "", 0},
  {"Stop", "停止", "", "", "", "", "", 0},
  {"If you don't hear anything, increase audio volume or check your speakers.", "若无声音，请调高音量或检查扬声器", "", "", "", "", "", 0},
  {"Audio Settings", "音频设置", "", "", "", "", "", 0},
  {"This vehicle doesn't have any audio capture device. Audio can't be used on this vehicle.", "该天空端未配备音频采集设备", "", "", "", "", "", 0},
  {"Microphone", "麦克风", "", "", "", "", "", 0},
  {"Select the type of microphone present on this vehicle, if any.", "选择天空端搭载的麦克风类型（如适用）", "", "", "", "", "", 0},
  {"Builtin", "内置", "", "", "", "", "", 0},
  {"External", "外置", "", "", "", "", "", 0},
  {"Your camera has a builtin microphone.", "您的摄像头配备内置麦克风", "", "", "", "", "", 0},
  {"Audio Stream", "音频流", "", "", "", "", "", 0},
  {"Enables or disables the audio stream.", "启用/禁用音频流传输", "", "", "", "", "", 0},
  {"Volume", "音量", "", "", "", "", "", 0},
  {"Audio recording volume.", "音频录制音量", "", "", "", "", "", 0},
  {"Quality", "质量", "", "", "", "", "", 0},
  {"Sets the quality of the audio stream.", "设置音频流质量", "", "", "", "", "", 0},
  {"Low", "低", "", "", "", "", "", 0},
  {"Normal", "标准", "", "", "", "", "", 0},
  {"High", "高", "", "", "", "", "", 0},
  {"Highest", "最高", "", "", "", "", "", 0},
  {"Buffering size", "缓冲大小", "", "", "", "", "", 0},
  {"How much to buffer audio. Longer buffering increase the consistency of audio stream but it adds delay.", "增大缓冲可提升音频流稳定性但会增加延迟", "", "", "", "", "", 0},
  {"Camera Settings", "摄像头设置", "", "", "", "", "", 0},
  {"Active Camera", "主摄像头", "", "", "", "", "", 0},
  {"Selects which camera should be active, if multiple cameras are present on this vehicle.", "当天空端搭载多摄像头时选择主摄像头", "", "", "", "", "", 0},
  {"Camera Type", "摄像头类型", "", "", "", "", "", 0},
  {"Autodetect the active camera type or force a particular camera type for the active camera.", "自动检测或强制指定主摄像头类型", "", "", "", "", "", 0},
  {"Autodetect", "自动检测", "", "", "", "", "", 0},
  {"Profile", "预设", "", "", "", "", "", 0},
  {"Brightness", "亮度", "", "", "", "", "", 0},
  {"Contrast", "对比度", "", "", "", "", "", 0},
  {"Saturation", "饱和度", "", "", "", "", "", 0},
  {"Sharpness", "锐度", "", "", "", "", "", 0},
  {"Hue", "色调", "", "", "", "", "", 0},
  {"Day/Night Mode", "昼夜模式", "", "", "", "", "", 0},
  {"Sets the mode to daylight (color and IR cut) or night (black and white, no IR cut).", "设置为日间（彩色+红外截止）或夜间（黑白+全光谱）模式", "", "", "", "", "", 0},
  {"Daylight", "日间模式", "", "", "", "", "", 0},
  {"Night B&W", "夜间模式", "", "", "", "", "", 0},
  {"White Balance", "白平衡", "", "", "", "", "", 0},
  {"WDR mode", "宽动态范围模式", "", "", "", "", "", 0},
  {"AGC stands for auto gain control. It is a part of auto exposure, in different light intensity, will try to adjust the gain of sensor to achieve the same image brightness.", "自动增益控制(AGC)，在不同光照下自动调节传感器增益以保持图像亮度", "", "", "", "", "", 0},
  {"Analog Gains", "模拟增益", "", "", "", "", "", 0},
  {"Sets the analog gains when the AWB is turned off.", "关闭自动白平衡时手动设置模拟增益", "", "", "", "", "", 0},
  {"Shutter Speed", "快门速度", "", "", "", "", "", 0},
  {"Sets shutter speed to auto or manual.", "设置快门速度为自动或手动模式", "", "", "", "", "", 0},
  {"Exposure", "曝光", "", "", "", "", "", 0},
  {"Metering", "测光", "", "", "", "", "", 0},
  {"Sets manual/auto ISO.", "设置ISO为自动/手动模式", "", "", "", "", "", 0},
  {"Video Stabilisation", "视频防抖", "", "", "", "", "", 0},
  {"Enables video stabilisation, if supported by the camera.", "启用摄像头支持的防抖功能", "", "", "", "", "", 0},
  {"Flip camera", "画面翻转", "", "", "", "", "", 0},
  {"Flips the camera video output upside down.", "垂直翻转摄像头视频输出", "", "", "", "", "", 0},
  {"IR Cut", "红外截止滤镜", "", "", "", "", "", 0},
  {"Turn IR cut filter on/off.", "启用/禁用红外截止滤镜", "", "", "", "", "", 0},
  {"Reset Profile", "重置预设", "", "", "", "", "", 0},
  {"Resets the current vehicle's camera paramters (brightness, contrast, etc) to the default values for the current profile.", "将当前天空端摄像头参数恢复为预设默认值", "", "", "", "", "", 0},
  {"Calibrate HDMI output", "校准HDMI输出", "", "", "", "", "", 0},
  {"Calibrate the colors, brightness and contrast on the controller display.", "校准地面端显示屏的色彩/亮度/对比度", "", "", "", "", "", 0},
  {"Show all camera settings", "显示全部摄像头设置", "", "", "", "", "", 0},
  {"Vehicle will reboot to update the firmware state.", "天空端将重启以更新固件状态", "", "", "", "", "", 0},
  {"Video Settings", "视频设置", "", "", "", "", "", 0},
  {"Video Settings, Active Camera:", "视频设置（主摄像头：）", "", "", "", "", "", 0},
  {"Video Profile", "视频预设", "", "", "", "", "", 0},
  {"Change all video params to get a particular desired video quality.", "调整所有视频参数以获得特定画质", "", "", "", "", "", 0},
  {"High Performance", "高性能", "", "", "", "", "", 0},
  {"High Quality", "高质量", "", "", "", "", "", 0},
  {"User", "自定义", "", "", "", "", "", 0},
  {"Video Codec", "视频编解码", "", "", "", "", "", 0},
  {"Change the codec used to encode the source video stream.", "更改视频流的编码格式", "", "", "", "", "", 0},
  {"Resolution", "分辨率", "", "", "", "", "", 0},
  {"Sets the resolution of the video stream.", "设置视频流分辨率", "", "", "", "", "", 0},
  {"Sets the FPS of the video stream.", "设置视频流帧率", "", "", "", "", "", 0},
  {"Keyframe interval (ms)", "关键帧间隔(ms)", "", "", "", "", "", 0},
  {"A keyframe is added every [n] miliseconds. Bigger keyframe values usually results in better quality video and lower bandwidth requirements but longer breakups if any.", "每[n]毫秒插入关键帧。较大值可提升画质但会增加信号中断时的恢复时间", "", "", "", "", "", 0},
  {"Video Bitrate (Mbps)", "视频码率(Mbps)", "", "", "", "", "", 0},
  {"Sets the video bitrate of the video stream generated by the camera.", "设置摄像头生成的视频流码率", "", "", "", "", "", 0},
  {"Sets a target desired bitrate for the video stream.", "设置视频流的目标码率", "", "", "", "", "", 0},
  {"Video Link Mode", "视频链路模式", "", "", "", "", "", 0},
  {"Set the way video link behaves: fixed broadcast video, or auto adaptive video link and stream.", "设置视频链路行为：固定广播或自适应调整", "", "", "", "", "", 0},
  {"Fixed One Way Video Link", "单向固定视频链路", "", "", "", "", "", 0},
  {"The radio video link will be one way broadcast only, no retransmissions will take place, video quality and video parameters will not be adjusted in real time.", "视频链路为单向广播，不进行重传，画质参数不会实时调整", "", "", "", "", "", 0},
  {"Bidirectional/Adaptive Video Link", "双向自适应视频链路", "", "", "", "", "", 0},
  {"Video and radio link parameters will be adjusted automatically in real time based on radio conditions.", "根据无线条件实时自动调整视频和链路参数", "", "", "", "", "", 0},
  {"Bidirectional/Adaptive Video Settings", "双向自适应视频设置", "", "", "", "", "", 0},
  {"Change retransmissions, auto keyframe, adaptive video settings.", "调整重传、自动关键帧等自适应参数", "", "", "", "", "", 0},
  {"Advanced Video Settings", "高级视频设置", "", "", "", "", "", 0},
  {"Change advanced video parameters for current profile.", "修改当前预设的高级视频参数", "", "", "", "", "", 0},
  {"Show all video settings", "显示全部视频设置", "", "", "", "", "", 0},
  {"Adaptive keyframe is turned on. Keyframe interval will be dynamically adjusted by Ruby. If you want to use a fixed keyframe, turn off Adaptive Keyframe from Bidirectional settings menu or set the video link as One Way.", "自适应关键帧已启用，将由Ruby动态调整间隔。如需固定间隔，请在双向设置菜单禁用此功能或切换为单向模式", "", "", "", "", "", 0},
  {"Can't use 2k,4k resolutions on Raspberry Pi controllers.", "树莓派地面端不支持2K/4K分辨率", "", "", "", "", "", 0},
  {"Incompatible settings", "不兼容的设置", "", "", "", "", "", 0},
  {"You have disabled all the radio uplinks. Adaptive video mode is not possible without any radio uplink. Enable radio uplinks from Menu->Vehicle->Radio.", "禁用所有上行链路后无法使用自适应视频模式，请通过 菜单->天空端->无线 重新启用", "", "", "", "", "", 0},
  {"Start Video Recording", "开始录像", "", "", "", "", "", 0},
  {"Stop Video Recording", "停止录像", "", "", "", "", "", 0},
  {"Your controller Raspberry Pi hardware supports only H264 video decoder. Can't use H265 codec.", "树莓派地面端仅支持H264解码", "", "", "", "", "", 0},
  {"Bidirectional Video Settings", "双向视频设置", "", "", "", "", "", 0},
  {"Retransmissions", "数据重传", "", "", "", "", "", 0},
  {"Enable retransmissions of video data.", "启用视频数据重传机制", "", "", "", "", "", 0},
  {"Retransmissions Algorithm", "重传策略", "", "", "", "", "", 0},
  {"Change the way retransmissions are requested.", "更改数据重传请求方式", "", "", "", "", "", 0},
  {"Regular", "常规", "", "", "", "", "", 0},
  {"Aggressive", "积极", "", "", "", "", "", 0},
  {"Auto Keyframing", "自动关键帧", "", "", "", "", "", 0},
  {"Automatic keyframe adjustment based on radio link conditions.", "根据无线链路状况自动调整关键帧间隔", "", "", "", "", "", 0},
  {"Max Auto Keyframe (ms)", "最大关键帧间隔(ms)", "", "", "", "", "", 0},
  {"Sets the max allowed keyframe interval (in miliseconds) when auto adjusting is enabled for video keyframe interval parameter.", "设置自动调整时的最大关键帧间隔", "", "", "", "", "", 0},
  {"Auto Video Quality", "自动画质调节", "", "", "", "", "", 0},
  {"Reduce the video quality when radio link quality goes down.", "无线链路质量下降时自动降低视频画质", "", "", "", "", "", 0},
  {"Adaptive Video Level", "自适应视频等级", "", "", "", "", "", 0},
  {"Automatically adjust video and radio transmission parameters when the radio link quality and the video link quality goes lower in order to improve range, video link and quality. Full: go to lowest video quality and best transmission if needed. Medium: Moderate lower quality.", "当无线电链路质量和视频链路质量降低时，自动调整视频和无线电传输参数，以提高范围、视频链路和质量。Full：如有需要将转到最低视频质量和最佳传输。Medium：中等质量。", "", "", "", "", "", 0},
  {"Medium", "Medium", "", "", "", "", "", 0},
  {"Full", "Full", "", "", "", "", "", 0},
  {"Algorithm", "算法", "", "", "", "", "", 0},
  {"Change the way adaptive video works.", "调整自适应视频的工作模式", "", "", "", "", "", 0},
  {"Auto Adjustment Strength", "自动调节强度", "", "", "", "", "", 0},
  {"How aggressive should the auto video link adjustments be (adaptive video and auto keyframe). 1 is the slowest adjustment strength, 10 is the fastest and most aggressive adjustment strength.", "设置视频链路自适应强度（1级最保守，10级最激进）", "", "", "", "", "", 0},
  {"Use Controller Feedback", "使用地面端反馈", "", "", "", "", "", 0},
  {"When vehicle adjusts video link params, use the feedback from the controller too in deciding the best video link params to be used.", "天空端调整视频参数时参考地面端的链路质量反馈", "", "", "", "", "", 0},
  {"Lower Quality On Link Lost", "链路中断时降质", "", "", "", "", "", 0},
  {"When vehicle looses connection from the controller, go to a lower video quality and lower radio datarate.", "当天空端与地面端断连时自动降低视频质量和无线速率", "", "", "", "", "", 0},
  {"User Interface Messages", "界面消息设置", "", "", "", "", "", 0},
  {"Display Units", "显示单位", "", "", "", "", "", 0},
  {"Changes how the OSD displays data: in metric system or imperial system.", "设置OSD显示使用公制或英制单位", "", "", "", "", "", 0},
  {"Persistent Messages", "永久消息", "", "", "", "", "", 0},
  {"User Interface Buttons", "界面按钮设置", "", "", "", "", "", 0},
  {"Swap +/- Buttons", "交换+/-按钮", "", "", "", "", "", 0},
  {"Swaps the function of + and - buttons.", "互换+和-按钮的功能", "", "", "", "", "", 0},
  {"Swap +/- Edit Buttons", "交换+/-编辑按钮", "", "", "", "", "", 0},
  {"Swaps the function of + and - buttons for editing values in UI.", "互换编辑数值时的+/-按钮功能", "", "", "", "", "", 0},
  {"Quick Action Button 1", "快捷按钮1", "", "", "", "", "", 0},
  {"Change what happens when you press the quick action button 1.", "设置快捷按钮1的触发动作", "", "", "", "", "", 0},
  {"Cycle OSD screen", "切换OSD界面", "", "", "", "", "", 0},
  {"Cycle OSD size", "调整OSD尺寸", "", "", "", "", "", 0},
  {"Take Picture", "拍照", "", "", "", "", "", 0},
  {"Video Recording", "录像控制", "", "", "", "", "", 0},
  {"Toggle OSD Off", "关闭OSD", "", "", "", "", "", 0},
  {"Toggle Stats Off", "关闭状态栏", "", "", "", "", "", 0},
  {"Toggle All Off", "关闭所有显示", "", "", "", "", "", 0},
  {"Relay Switch", "中继切换", "", "", "", "", "", 0},
  {"Switch Camera Profile", "切换摄像头预设", "", "", "", "", "", 0},
  {"RC Output On/Off", "遥控开关", "", "", "", "", "", 0},
  {"Rotary Encoder Function", "旋钮编码器功能", "", "", "", "", "", 0},
  {"Freeze OSD", "冻结OSD", "", "", "", "", "", 0},
  {"Cycle Favorite Vehicles", "轮换常用天空端", "", "", "", "", "", 0},
  {"Quick Action Button 2", "快捷按钮2", "", "", "", "", "", 0},
  {"Change what happens when you press the quick action button 2.", "设置快捷按钮2的触发动作", "", "", "", "", "", 0},
  {"Quick Action Button 3", "快捷按钮3", "", "", "", "", "", 0},
  {"Change what happens when you press the quick action button 3.", "设置快捷按钮3的触发动作", "", "", "", "", "", 0},
  {"Rotary Encoder Function", "旋钮编码器功能", "", "", "", "", "", 0},
  {"Sets the function of the optional rotary encoder. Long press the rotary encoder for 10 seconds to revert to Menu function.", "设置旋钮编码器功能（长按10秒恢复菜单导航功能）", "", "", "", "", "", 0},
  {"Menu Navigation", "菜单导航", "", "", "", "", "", 0},
  {"Camera Adjustment", "摄像头调节", "", "", "", "", "", 0},
  {"Rotary Encoder Speed", "旋钮灵敏度", "", "", "", "", "", 0},
  {"Sets the speed of the optional rotary encoder.", "设置旋钮编码器的调节速度", "", "", "", "", "", 0},
  {"Normal", "标准", "", "", "", "", "", 0},
  {"Slower", "慢速", "", "", "", "", "", 0},
  {"Rotary Encoder 2 Function", "副旋钮功能", "", "", "", "", "", 0},
  {"Sets the function of the secondary optional rotary encoder. Long press the secondary rotary encoder for 10 seconds to revert to Menu function.", "设置副旋钮编码器功能（长按10秒恢复默认）", "", "", "", "", "", 0},
  {"Rotary Encoder 2 Speed", "副旋钮灵敏度", "", "", "", "", "", 0},
  {"Sets the speed of the secondary optional rotary encoder.", "设置副旋钮编码器的调节速度 ", "", "", "", "", "", 0},
  {"Enabling/disabling RC link during flight is dangerous. Proceed with caution.", "警告：飞行中禁用遥控链路极其危险！", "", "", "", "", "", 0},
  {"Vehicle Management", "天空端管理", "", "", "", "", "", 0},
  {"Get Hardware Info", "获取硬件信息", "", "", "", "", "", 0},
  {"Gets the hardware capabilities of the vehicle.", "读取天空端的硬件配置信息", "", "", "", "", "", 0},
  {"Get Config Info", "获取配置信息", "", "", "", "", "", 0},
  {"Gets the current configuration of the vehicle.", "读取天空端的当前参数配置", "", "", "", "", "", 0},
  {"Get Modules Info", "获取模块信息", "", "", "", "", "", 0},
  {"Gets the current detected and loaded modules on the vehicle.", "检测天空端当前加载的硬件模块", "", "", "", "", "", 0},
  {"Core Plugins", "核心插件", "", "", "", "", "", 0},
  {"Manage the core plugins on this vehicle.", "管理天空端的核心插件", "", "", "", "", "", 0},
  {"Export Model Settings", "导出模型设置", "", "", "", "", "", 0},
  {"Exports the model settings to a USB stick.", "将当前模型设置导出到U盘", "", "", "", "", "", 0},
  {"Import Model Settings", "导入模型设置", "", "", "", "", "", 0},
  {"Imports the model settings from a USB stick.", "从U盘导入模型设置", "", "", "", "", "", 0},
  {"Update Software", "软件更新", "", "", "", "", "", 0},
  {"Updates the software on the vehicle.", "更新天空端固件", "", "", "", "", "", 0},
  {"Reset to defaults", "恢复默认设置", "", "", "", "", "", 0},
  {"Resets all parameters for this vehicle to the default configuration (except for frequency, vehicle ID and name).", "重置天空端所有参数为默认值（频率、ID和名称除外）", "", "", "", "", "", 0},
  {"Factory Reset", "恢复出厂设置", "", "", "", "", "", 0},
  {"Resets the vehicle as it comes after a fresh install. All settings (including vehicle name, frequency, etc) will be reset to default values.", "将天空端完全重置为初始状态（包括名称、频率等所有参数）", "", "", "", "", "", 0},
  {"Restart", "重启", "", "", "", "", "", 0},
  {"Restarts the vehicle.", "重启天空端", "", "", "", "", "", 0},
  {"Delete", "删除", "", "", "", "", "", 0},
  {"Delete this vehicle from your control list.", "从控制列表中移除该天空端", "", "", "", "", "", 0},
  {"There are no vehicle settings files on the USB stick.", "未在U盘中找到天空端配置文件", "", "", "", "", "", 0},
  {"All parameters (including vehicle name, radio frequency, etc) and state will be reset to default values as after a fresh instalation.", "所有参数（包括天空端名称、频率等）将恢复为初始默认值", "", "", "", "", "", 0},
  {"You will need to search and pair with the vehicle again after that.", "操作完成后需重新搜索配对天空端", "", "", "", "", "", 0},
  {"Warning: You have the RC link enabled, the vehicle flight controller will go into RC failsafe mode during reboot.", "警告：遥控链路启用时重启，飞控将进入失控保护模式", "", "", "", "", "", 0},
  {"Telemetry Settings", "遥测设置", "", "", "", "", "", 0},
  {"Auto Detect Telemetry Settings", "自动检测设置", "", "", "", "", "", 0},
  {"Auto detect the telemetry type generated by the flight controller and the serial port and serial speed connected to the vehicle.", "自动检测飞控生成的遥测类型及天空端串口参数", "", "", "", "", "", 0},
  {"FC Telemetry Type", "飞控遥测类型", "", "", "", "", "", 0},
  {"The telemetry type that is sent/received from the flight controller. This should match the telemetry type generated by the flight controller.", "飞控收发使用的遥测协议类型，需与飞控生成的类型匹配", "", "", "", "", "", 0},
  {"Allow any FC SysId", "允许任意飞控系统ID", "", "", "", "", "", 0},
  {"Receive and use telemetry messages from any system id on the flight controller, or just from the main pilot system (sysid=1).", "接收来自飞控任意系统ID的遥测（默认仅接收主飞控sysid=1的数据）", "", "", "", "", "", 0},
  {"Ignore FC Messages", "忽略飞控消息", "", "", "", "", "", 0},
  {"Ignore text messages from FC, do not display them in the UI.", "不显示飞控发送的文本消息", "", "", "", "", "", 0},
  {"Remove duplicate msgs", "去除重复消息", "", "", "", "", "", 0},
  {"Removes duplicate messages that are generated by the flight controller, if any.", "过滤飞控生成的重复遥测消息", "", "", "", "", "", 0},
  {"Force Always Armed", "强制持续解锁状态", "", "", "", "", "", 0},
  {"Force the Armed state, permanently, for flight controllers that do not have an arm/disarm state or for custom MAVLink streams.", "对不支持解锁状态的飞控或自定义MAVLink数据流强制保持解锁状态", "", "", "", "", "", 0},
  {"Vehicle Serial Port", "天空端串口", "", "", "", "", "", 0},
  {"The Ruby vehicle port at which the flight controller connects to.", "飞控连接至Ruby天空端的通信端口", "", "", "", "", "", 0},
  {"Vehicle Serial Baudrate", "天空端串口波特率", "", "", "", "", "", 0},
  {"Sets the baud rate between flight controller and Ruby on the vehicle side. Should match the serial speed that the flight controller generates. Higher is better.", "设置飞控与天空端的通信速率（需与飞控配置匹配，越高越好）", "", "", "", "", "", 0},
  {"Has GPS", "GPS配置", "", "", "", "", "", 0},
  {"Sets how many GPS units are configured on the vehicle. Ruby uses GPS data for OSD display.", "设置天空端GPS模块数量（用于OSD显示）", "", "", "", "", "", 0},
  {"No GPS", "无GPS", "", "", "", "", "", 0},
  {"Refresh rate (Hz)", "刷新率(Hz)", "", "", "", "", "", 0},
  {"How many times per second the flight controller telemetry gets sent from vehicle to controller.", "设置遥测数据从天空端到地面端每秒发送的次数", "", "", "", "", "", 0},
  {"Allow spectators", "允许观众模式", "", "", "", "", "", 0},
  {"Allows spectators to read the telemetry stream and display it in OSD.", "允许其他设备以观众模式读取遥测数据并在OSD显示", "", "", "", "", "", 0},
  {"Telemetry Options", "遥测选项", "", "", "", "", "", 0},
  {"Enables or disables the telemetry upload from controller to vehicle.", "启用/禁用地面向天空端的遥测上传", "", "", "", "", "", 0},
  {"Bidirectional", "双向模式", "", "", "", "", "", 0},
  {"Read Only", "只读模式", "", "", "", "", "", 0},
  {"Request data streams", "请求数据流", "", "", "", "", "", 0},
  {"Enables the request of the telemetry data streams from vehicle.", "启用从天空端请求遥测数据流", "", "", "", "", "", 0},
  {"Controller MAVLink SysId", "地面端MAVLink系统ID", "", "", "", "", "", 0},
  {"Sets the MAVLink SysId for Ruby controller as it will be seen by the vehicle flight controller.", "设置地面端在飞控系统中的MAVLink标识符", "", "", "", "", "", 0},
  {"Note: The controller MAVLink SysId must match the parameter SYSID_MYGCS set on flight controller using Mission Planner or QGC.", "注：需与飞控参数SYSID_MYGCS（通过Mission Planner/QGC设置）保持一致", "", "", "", "", "", 0},
  {"Can't use serial port", "串口不可用", "", "", "", "", "", 0},
  {"The serial port you selected can't be used for telemetry connection to flight controller as it's used for a SiK radio interface.", "所选串口已被SiK射频模块占用，无法用于飞控遥测", "", "", "", "", "", 0},
  {"User Data Link Disabled", "自定义数据链路已禁用", "", "", "", "", "", 0},
  {"The serial port was used by your custom data link. It was reasigned to the telemetry link.", "原自定义数据链路使用的串口已被重新分配给遥测链路", "", "", "", "", "", 0},
  {"Vehicle Actions", "天空端操作", "", "", "", "", "", 0},
  {"Can't get vehicle info!", "无法获取天空端信息！", "", "", "", "", "", 0},
  {"Actions", "操作", "", "", "", "", "", 0},
  {"Select", "选择", "", "", "", "", "", 0},
  {"Make this vehicle the active one.", "设为当前天空端", "", "", "", "", "", 0},
  {"Remove from favorites", "从常用列表移除", "", "", "", "", "", 0},
  {"Removes this vehicle from the list of favorite vehicles.", "将该天空端移出常用列表", "", "", "", "", "", 0},
  {"Add to favorites", "添加到常用列表", "", "", "", "", "", 0},
  {"Add this vehicle to the list of favorite vehicles. You can switch quickly between favorite vehicles using a Quick Button action.", "加入常用列表（可通过快捷按钮快速切换）", "", "", "", "", "", 0},
  {"Delete", "删除", "", "", "", "", "", 0},
  {"Deletes this vehicle.", "永久删除该天空端", "", "", "", "", "", 0},
  {"Switching vehicle...", "正在切换天空端...", "", "", "", "", "", 0},
  {"Your vehicle has audio enabled but no audio capture device", "天空端音频已启用但无采集设备", "", "", "", "", "", 0},
  {"Your vehicle has audio enabled but your controller can't output audio.", "天空端音频已启用但地面端无输出设备", "", "", "", "", "", 0},
  {"Received vehicle settings.", "已接收天空端设置", "", "", "", "", "", 0},
  {"Synchronized vehicle settings.", "天空端设置同步完成", "", "", "", "", "", 0},
  {"If you just installed a vehicle, power up your vehicle. The connection will be made automatically when that vehicle is in radio range.", "信号范围内的新天空端将在通电后自动连接", "", "", "", "", "", 0},
  {"Or press the [Menu] key to open up the menu and use [Search] menu to search for other vehicles to connect to.", "或按[菜单]键手动搜索其他天空端", "", "", "", "", "", 0},
  {"Power up your vehicle. The connection will be made automatically when the vehicle is in radio range.", "信号范围内的天空端将在通电后自动连接", "", "", "", "", "", 0},
  {"Or press the [Menu] key to open up the menu and switch to another vehicle or search for other vehicles.", "或按[菜单]键切换/搜索其他天空端", "", "", "", "", "", 0},
  {"Another unpaired vehicle is using the same frequency as your current vehicle. Search and connect (pair) to this new vehicle or power it off as it will impact your radio link quality.", "检测到未配对天空端使用相同频段，请配对或关闭以免干扰", "", "", "", "", "", 0},
  {"The radio link with the vehicle is lost. Will reconnect automatically when in range.", "无线链路中断，恢复信号后自动重连", "", "", "", "", "", 0},
  {"Flight controller telemetry missing", "飞控遥测丢失", "", "", "", "", "", 0},
  {"Flight controller telemetry recovered", "飞控遥测恢复", "", "", "", "", "", 0},
  {"Video stream was restarted on vehicle.", "天空端视频流已重启", "", "", "", "", "", 0},
  {"Radio streams where restarted on vehicle.", "天空端无线数据流已重启", "", "", "", "", "", 0},
  {"Controller router process is malfunctioning! Restarting it.", "地面端路由进程异常！正在重启", "", "", "", "", "", 0},
  {"Controller telemetry process is malfunctioning! Restarting it.", "地面端遥测进程异常！正在重启", "", "", "", "", "", 0},
  {"Radio hardware error", "射频硬件错误", "", "", "", "", "", 0},
  {"One of you radio interfaces have broken!", "射频接口故障！", "", "", "", "", "", 0},
  {"Please check your hardware configuration for overheating issues or power supply issues or USB connections issues.", "请检查硬件散热、供电及USB连接", "", "", "", "", "", 0},
  {"Video file processing failed.", "视频文件处理失败", "", "", "", "", "", 0},
  {"Video file processing complete.", "视频文件处理完成", "", "", "", "", "", 0},
  {"RC is enabled on current vehicle and the input controller device is missing!", "当前天空端已启用遥控但未检测到输入设备！", "", "", "", "", "", 0},
  {"RC is enabled on current vehicle and the detected RC input controller device is different from the one setup on the vehicle!", "检测到的遥控设备与天空端配置不匹配！", "", "", "", "", "", 0},
  {"OSD / Instruments Settings", "OSD/仪表设置", "", "", "", "", "", 0},
  {"General OSD Settings", "OSD全局设置", "", "", "", "", "", 0},
  {"Sets global settings for all OSD/instruments/gauges", "设置所有OSD元素/仪表/指示器的全局参数", "", "", "", "", "", 0},
  {"OSD Size, Color, Fonts", "OSD颜色字体大小设置", "", "", "", "", "", 0},
  {"Sets colors, size and fonts for OSD.", "设置OSD的显示颜色、尺寸和字体", "", "", "", "", "", 0},
  {"OSD Layouts and Settings", "OSD布局设置", "", "", "", "", "", 0},
  {"Screen", "界面", "", "", "", "", "", 0},
  {"Changes the active screen of the OSD elements and what information you see on this screen.", "切换OSD界面及显示内容", "", "", "", "", "", 0},
  {"Enables or disables this screen", "启用/禁用本界面", "", "", "", "", "", 0},
  {"Only plugins", "仅插件", "", "", "", "", "", 0},
  {"Layout", "布局", "", "", "", "", "", 0},
  {"Set the default layout of this OSD screen (what elements are shown on this screen).", "设置当前OSD界面的默认元素布局", "", "", "", "", "", 0},
  {"No elements", "无元素", "", "", "", "", "", 0},
  {"Minimal", "极简", "", "", "", "", "", 0},
  {"Compact", "紧凑", "", "", "", "", "", 0},
  {"Default", "默认", "", "", "", "", "", 0},
  {"Custom", "自定义", "", "", "", "", "", 0},
  {"Font Size", "字体大小", "", "", "", "", "", 0},
  {"Increase/decrease OSD font size for current screen.", "调整当前OSD界面的字体尺寸", "", "", "", "", "", 0},
  {"Background Type", "背景类型", "", "", "", "", "", 0},
  {"Change if and how the background behind OSD elements is shown.", "设置OSD元素的背景显示方式", "", "", "", "", "", 0},
  {"On text only", "仅文字背景", "", "", "", "", "", 0},
  {"As Bars", "条状背景", "", "", "", "", "", 0},
  {"Background Transparency", "背景透明度", "", "", "", "", "", 0},
  {"Change how transparent the OSD background is for current screen.", "设置当前OSD界面背景的透明程度", "", "", "", "", "", 0},
  {"Max", "Max", "", "", "", "", "", 0},
  {"Medium", "Medium", "", "", "", "", "", 0},
  {"Minimum", "Minimum", "", "", "", "", "", 0},
  {"Highlight Changing Elements", "高亮变化元素", "", "", "", "", "", 0},
  {"Highlight when important OSD elements change (i.e. radio modulation schemes).", "当关键OSD元素（如射频调制模式）变化时高亮显示", "", "", "", "", "", 0},
  {"Don't show FC messages", "不显示飞控消息", "", "", "", "", "", 0},
  {"Do not show messages/texts from flight controller.", "隐藏飞控发送的文本消息", "", "", "", "", "", 0},
  {"Show MSP OSD Elements", "显示MSP OSD元素", "", "", "", "", "", 0},
  {"Render the MSP OSD Elements", "渲染MSP协议传输的OSD元素", "", "", "", "", "", 0},
  {"Layout OSD Elements", "OSD元素布局", "", "", "", "", "", 0},
  {"Configure which OSD elements show up on current screen", "配置当前界面显示的OSD元素", "", "", "", "", "", 0},
  {"Layout OSD Widgets & Gauges", "OSD部件布局", "", "", "", "", "", 0},
  {"Configure which OSD widgets and gauges show up on current screen and where to show them.", "配置当前界面显示的仪表/指示器及其位置", "", "", "", "", "", 0},
  {"Layout OSD Plugins", "OSD插件布局", "", "", "", "", "", 0},
  {"Show/Hide/Configure the custom OSD plugins that are installed on the controller.", "管理地面端安装的自定义OSD插件", "", "", "", "", "", 0},
  {"Layout OSD Stats Windows", "OSD统计窗口", "", "", "", "", "", 0},
  {"Configure which statistics windows show up on current screen.", "配置当前界面显示的统计窗口", "", "", "", "", "", 0},
  {"Your vehicle radio modules have been reinitialized", "天空端射频模块已重新初始化", "", "", "", "", "", 0},
  {"Your vehicle radio modules have been restarted due to a harware issue. Please check your wiring and power supply on the vehicle.", "因硬件问题已重启射频模块，请检查天空端线路和供电", "", "", "", "", "", 0},
  {"Your vehicle is overloaded. Can't keep up processing data for sending (EC). Lower your video bitrate or EC.", "天空端过载！无法维持数据传输(EC)，请降低视频码率或EC强度", "", "", "", "", "", 0},
  {"Vehicle: Radio link to controller is lost", "天空端：与地面端的无线链路中断", "", "", "", "", "", 0},
  {"Vehicle: Radio link to controller recovered.", "天空端：与地面端的无线链路恢复", "", "", "", "", "", 0},
  {"Completed", "完成", "", "", "", "", "", 0},
  {"Failed!", "失败！", "", "", "", "", "", 0},
  {"Your vehicle is sending H265 video. Your controller does not support H265 video decoding. Switch your vehicle to H264 video encoding from vehicle's Video menu.", "天空端使用H265编码，但地面端不支持H265解码，请在视频菜单切换为H264", "", "", "", "", "", 0},
  {"Unsupported Video Type", "不支持的视频格式", "", "", "", "", "", 0},
  {"Please wait...", "请稍候...", "", "", "", "", "", 0},
  {"A new USB input device was detected", "检测到新USB输入设备", "", "", "", "", "", 0},
  {"A USB input device was removed", "USB输入设备已移除", "", "", "", "", "", 0},
  {"OSD Elements", "OSD元素", "", "", "", "", "", 0},
  {"OSD Elements Arrangement", "OSD元素排列", "", "", "", "", "", 0},
  {"How the OSD elements are arranged on the screen: fluid around margins or only on the left/right sides of the screen.", "设置OSD元素在屏幕上的排列方式：边缘自适应或固定左右布局", "", "", "", "", "", 0},
  {"Fluid", "自适应", "", "", "", "", "", 0},
  {"Left/Right", "左右布局", "", "", "", "", "", 0},
  {"Background bars", "背景条", "", "", "", "", "", 0},
  {"Shows background bars behind the OSD to increase readability", "显示背景条增强OSD可读性", "", "", "", "", "", 0},
  {"Intruments/Gauges Settings", "仪表设置", "", "", "", "", "", 0},
  {"Show Speed/Alt", "显示速度/高度", "", "", "", "", "", 0},
  {"Shows the speed and altitude instruments", "显示速度和高度仪表", "", "", "", "", "", 0},
  {"Show Heading", "显示航向", "", "", "", "", "", 0},
  {"Shows the heading instrument.", "显示航向指示器", "", "", "", "", "", 0},
  {"Show Altitude Graph/Glide", "显示高度曲线/滑翔比", "", "", "", "", "", 0},
  {"Shows the altitude graph and glide efficiency.", "显示高度变化曲线及滑翔效率", "", "", "", "", "", 0},
  {"Voltage/Current", "电压/电流", "", "", "", "", "", 0},
  {"Shows the voltage/current on the OSD.", "在OSD显示电压和电流值", "", "", "", "", "", 0},
  {"Voltage per cell", "单电芯电压", "", "", "", "", "", 0},
  {"Shows also the voltage per cell of the battery.", "同时显示电池各组电芯电压", "", "", "", "", "", 0},
  {"Controller Voltage & Current", "地面端电压电流", "", "", "", "", "", 0},
  {"Shows controller voltage and current on the OSD.", "在OSD显示地面端供电状态", "", "", "", "", "", 0},
  {"Distance", "返航距离", "", "", "", "", "", 0},
  {"Shows the distance from home on the OSD.", "显示当前位置与返航点的距离", "", "", "", "", "", 0},
  {"Total distance", "总飞行距离", "", "", "", "", "", 0},
  {"Shows on the OSD the total distance traveled, not just current distance from home.", "显示累计飞行距离（非实时返航距离）", "", "", "", "", "", 0},
  {"Speed", "速度", "", "", "", "", "", 0},
  {"Shows the ground and/or air speed on the OSD.", "设置OSD显示地速或空速", "", "", "", "", "", 0},
  {"Ground Speed", "地速", "", "", "", "", "", 0},
  {"Air Speed", "空速", "", "", "", "", "", 0},
  {"Both", "全部显示", "", "", "", "", "", 0},
  {"Altitude", "高度", "", "", "", "", "", 0},
  {"Shows the altitude on the OSD.", "在OSD上显示飞行高度", "", "", "", "", "", 0},
  {"Home", "返航指示", "", "", "", "", "", 0},
  {"Shows the home heading on the OSD.", "显示返航方向指示器", "", "", "", "", "", 0},
  {"Mirror home arrow", "镜像返航箭头", "", "", "", "", "", 0},
  {"Flips the rotation of the home arrow.", "反转返航箭头的旋转方向", "", "", "", "", "", 0},
  {"Home arrow rotation", "返航箭头旋转", "", "", "", "", "", 0},
  {"Changes the orientation of the home arrow by a set amount.", "调整返航箭头的基准角度", "", "", "", "", "", 0},
  {"GPS Satellites", "GPS卫星", "", "", "", "", "", 0},
  {"Shows the GPS satellites information.", "显示GPS卫星信息", "", "", "", "", "", 0},
  {"GPS position", "GPS坐标", "", "", "", "", "", 0},
  {"Shows the current GPS position (long,lat).", "显示当前经纬度坐标(long,lat)", "", "", "", "", "", 0},
  {"Scrambled", "加密显示", "", "", "", "", "", 0},
  {"Flight mode", "飞行模式", "", "", "", "", "", 0},
  {"Shows flight mode on the OSD.", "显示当前飞控模式", "", "", "", "", "", 0},
  {"Only when changing", "仅模式切换时显示", "", "", "", "", "", 0},
  {"Time", "时间", "", "", "", "", "", 0},
  {"Shows the arm/flight time on the OSD.", "显示解锁时长/飞行时间", "", "", "", "", "", 0},
  {"Yes (Top)", "显示(顶部)", "", "", "", "", "", 0},
  {"Yes (Bottom)", "显示(底部)", "", "", "", "", "", 0},
  {"Wind", "风速", "", "", "", "", "", 0},
  {"Shows the wind direction and speed on the OSD.", "显示风向和风速", "", "", "", "", "", 0},
  {"Temperature", "温度", "", "", "", "", "", 0},
  {"Shows the temperature (if reported by the flight controller) on the OSD.", "显示飞控回传的温度数据", "", "", "", "", "", 0},
  {"Throttle", "油门", "", "", "", "", "", 0},
  {"Shows the throttle on the OSD.", "显示油门百分比", "", "", "", "", "", 0},
  {"Pitch", "俯仰角", "", "", "", "", "", 0},
  {"Shows vehicle pitch on the OSD.", "显示飞行器俯仰角度", "", "", "", "", "", 0},
  {"Vehicle CPU Info", "天空端CPU信息", "", "", "", "", "", 0},
  {"Shows vehicle CPU info on the OSD.", "显示天空端处理器状态", "", "", "", "", "", 0},
  {"Controller CPU Info", "地面端CPU信息", "", "", "", "", "", 0},
  {"Shows controller CPU info on the OSD.", "显示地面端处理器状态", "", "", "", "", "", 0},
  {"Video Mode", "视频模式", "", "", "", "", "", 0},
  {"Shows current video mode on the OSD.", "显示当前视频传输模式", "", "", "", "", "", 0},
  {"Video Mbps", "视频码率(Mbps)", "", "", "", "", "", 0},
  {"Shows the video link total Mbps and video Mbps generated by the camera.", "显示视频链路总码率及摄像头原始码率", "", "", "", "", "", 0},
  {"Video Info (Extended)", "视频详情(扩展)", "", "", "", "", "", 0},
  {"Shows the video link total Mbps and video Mbps generated by the camera.", "显示视频编解码详细信息", "", "", "", "", "", 0},
  {"Radio Links", "无线链路", "", "", "", "", "", 0},
  {"Shows info about the radio links (Downlinks = controller Rx, from vehicle to controller; Uplinks = vehicle Rx, from controller to vehicle) in the OSD.", "显示上下行链路状态（下行：天空端→地面端，上行：地面端→天空端）", "", "", "", "", "", 0},
  {"Downlinks", "下行链路", "", "", "", "", "", 0},
  {"Uplinks", "上行链路", "", "", "", "", "", 0},
  {"   Radio Links Info", "   无线链路信息", "", "", "", "", "", 0},
  {"What info to show about the radio links (uplinks and downlinks) in the OSD.", "设置OSD显示的无线链路参数类型", "", "", "", "", "", 0},
  {"Quality Bars", "质量柱状图", "", "", "", "", "", 0},
  {"Quality Numbers", "质量数值", "", "", "", "", "", 0},
  {"   Radio Interfaces Info", "   射频接口信息", "", "", "", "", "", 0},
  {"Shows information in OSD radio links about the radio interfaces associated with each radio link.", "在OSD显示各射频接口的详细状态", "", "", "", "", "", 0},
  {"Basic", "基础", "", "", "", "", "", 0},
  {"Full", "完整", "", "", "", "", "", 0},
  {"RC RSSI", "遥控信号强度", "", "", "", "", "", 0},
  {"Shows the RC RSSI indicator on the OSD.", "显示遥控信号强度指示器", "", "", "", "", "", 0},
  {"Signal strength bars", "信号强度条", "", "", "", "", "", 0},
  {"Shows signal strength bars on the OSD.", "显示信号强度柱状图", "", "", "", "", "", 0},
  {"Signal bars position", "信号条位置", "", "", "", "", "", 0},
  {"Sets the position on the screen of the signal strength bars.", "设置信号强度条的屏幕位置", "", "", "", "", "", 0},
  {"Top", "顶部", "", "", "", "", "", 0},
  {"Bottom", "底部", "", "", "", "", "", 0},
  {"Left", "左侧", "", "", "", "", "", 0},
  {"Right", "右侧", "", "", "", "", "", 0},
  {"RC Sticks and channels", "遥控杆量通道", "", "", "", "", "", 0},
  {"Shows the RC input sticks and RC channels on the OSD as they are actually reported back by the vehicle.", "显示天空端回传的实际遥控通道值", "", "", "", "", "", 0},
  {"Grid Overlay", "网格叠加", "", "", "", "", "", 0},
  {"Shows a grid over the screen.", "在画面中显示辅助网格", "", "", "", "", "", 0},
  {"Crosshair", "十字准星", "", "", "", "", "", 0},
  {"Diagonal Lines", "对角线", "", "", "", "", "", 0},
  {"Thirds Lines", "三分线", "", "", "", "", "", 0},
  {"Thirds Lines Small", "简化三分线", "", "", "", "", "", 0},
  {"OSD settings", "OSD设置", "", "", "", "", "", 0},
  {"Changing Frequency", "正在切换频率", "", "", "", "", "", 0},
  {"   Radio Links Numbers", "   无线链路数值", "", "", "", "", "", 0},
  {"What numerical info to show about the radio links (uplinks and downlinks) in the OSD.", "设置OSD显示的无线链路量化参数", "", "", "", "", "", 0},
  {"Quick Pairing Setup", "快速配对设置", "", "", "", "", "", 0},
  {"Advanced Video Settings (Expert)", "高级视频设置(专家模式)", "", "", "", "", "", 0},
  {"Change advanced vehicle encoding settings (for expert users)", "修改天空端视频编码高级参数（仅限专家用户）", "", "", "", "", "", 0},
  {"Settings for unknown video profile:", "未知视频预设参数：", "", "", "", "", "", 0},
  {"Settings for High Performance video profile:", "高性能模式参数：", "", "", "", "", "", 0},
  {"Settings for High Quality video profile:", "高质量模式参数：", "", "", "", "", "", 0},
  {"Settings for User video profile:", "自定义模式参数：", "", "", "", "", "", 0},
  {"Enable Vehicle Local HDMI Output", "启用天空端本地HDMI输出", "", "", "", "", "", 0},
  {"Enables or disables video output the the HDMI port on the vehicle.", "启用/禁用天空端HDMI接口的视频输出", "", "", "", "", "", 0},
  {"Noise Level", "噪点等级", "", "", "", "", "", 0},
  {"Sets the video noise level. Lower values means better performance but more noise in the live video.", "设置视频噪点处理强度（值越低性能越好但实时画面噪点更多）", "", "", "", "", "", 0},
  {"Data & Error Correction Settings", "数据与纠错设置", "", "", "", "", "", 0},
  {"Packet size", "数据包大小", "", "", "", "", "", 0},
  {"How big is each indivisible video packet over the air link. No major impact in link quality. Smaller packets and more EC packets increase the chance of error correction but also increases the video latency.", "设置无线视频数据包大小。较小值提升纠错能力但会增加延迟", "", "", "", "", "", 0},
  {"Data Packets in a Block", "数据包每块数量", "", "", "", "", "", 0},
  {"How many indivisible packets are in a block. This has an impact on link recovery and error correction. Bigger values might increase the delay in video stream when link is degraded, but also increase the chance of error correction.", "设置每个数据块包含的数据包数。较大值增强纠错能力但会增大延迟", "", "", "", "", "", 0},
  {"EC Packets in a Block", "纠错包数量", "", "", "", "", "", 0},
  {"How many error correcting packets to add to a block.Bigger values increase the chance of error correction but decrease the usable link data rate buget.", "设置每数据块的纠错包数量（增加可提升纠错能力但降低有效带宽）", "", "", "", "", "", 0},
  {"EC Spreading Factor", "纠错扩散系数", "", "", "", "", "", 0},
  {"Spreads the EC packets accross multiple video blocks.", "将纠错包分散到多个视频块中", "", "", "", "", "", 0},
  {"H264 Encoder Settings", "H264编码设置", "", "", "", "", "", 0},
  {"Reset Profile", "重置预设", "", "", "", "", "", 0},
  {"Resets the current video profile to the default values.", "将当前视频预设恢复为默认值", "", "", "", "", "", 0},
  {"Slice units might not work properly when a Raspberry Pi controller is paired with a vehicle running on OpenIPC hardware.", "树莓派地面端与OpenIPC天空端配对时切片功能可能异常", "", "", "", "", "", 0},
  {"Vehicle Alarms and Warnings Settings", "天空端告警设置", "", "", "", "", "", 0},
  {"Enable Voltage Alarm", "启用电压告警", "", "", "", "", "", 0},
  {"Shows an alarm on screen when vehicle battery voltage drops below a value.", "当电池电压低于阈值时显示OSD告警", "", "", "", "", "", 0},
  {"Alarm voltage", "告警电压", "", "", "", "", "", 0},
  {"Voltage at which the alarm will trigger.", "触发电压告警的阈值", "", "", "", "", "", 0},
  {"Enable Motor Alarm", "启用电机告警", "", "", "", "", "", 0},
  {"Shows an alarm on screen when throttle is active but motor is not responding (not consumming current). Set the threshold for current consumed by the vehicle when idle. Works only with MAVLink telemetry.", "油门激活但电流不足时显示告警（需设置怠速电流阈值，仅MAVLink遥测有效）", "", "", "", "", "", 0},
  {"Pitch/Roll warning angle", "俯仰/横滚告警角度", "", "", "", "", "", 0},
  {"Pitch and roll angle at witch to show a OSD warning indication about attitude (0 for disabled).", "设置触发姿态告警的角度阈值（0为禁用）", "", "", "", "", "", 0},
  {"Link to Controller Lost Alarm", "地面端断连告警", "", "", "", "", "", 0},
  {"Shows an alarm when the vehicle looses connection with the controller. That is, vehicle does not receive the uplink data for a period of time.", "当天空端持续未收到上行数据时显示告警", "", "", "", "", "", 0},
  {"Flash OSD on Telemetry Lost", "遥测丢失时OSD闪烁", "", "", "", "", "", 0},
  {"Flashes the OSD whenever a telemetry data packet is lost.", "每当丢失遥测数据包时闪烁OSD元素", "", "", "", "", "", 0},
  {"On individual OSD screens", "针对每个独立OSD界面", "", "", "", "", "", 0},
  {"Telemetry Detection Wizard", "", "", "", "", "", "", 0},
  {"Done", "", "", "", "", "", "", 0},
  {"Video functionality has changed. You need to update your vehicle sowftware.", "", "", "", "", "", "", 0},
  {"Video block size", "", "", "", "", "", "", 0},
  {"Error Correction", "", "", "", "", "", "", 0},
  {"How much error correction data to add to the video data.", "", "", "", "", "", "", 0},
  {"Vehicle OTA software update required", "", "", "", "", "", "", 0},
  {"Controller software update required", "", "", "", "", "", "", 0},
  {"Video protocols have changed. You must update your controller", "", "", "", "", "", "", 0},
  {"Video Buffers Use:", "", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0},




  {"", "", "", "", "", "", "", 0},
  {"", "", "", "", "", "", "", 0}
};

#else
type_localized_strings s_LocalizedStringsTable[] = 
{
  {"NA", "NA", "NA", "NA", "NA", "NA", "NA", 0}
};
#endif

type_localized_strings* string_get_table()
{
   return s_LocalizedStringsTable;
}

int string_get_table_size()
{
   return sizeof(s_LocalizedStringsTable)/sizeof(s_LocalizedStringsTable[0]);
}